### PR TITLE
Bottom Bar Beautification + Tweaks

### PR DESCRIPTION
**Pull request by redthefed**
Made adjustments to bottom bar formatting to prevent text jitter.  Also changed the maximum value for displayed times from over 9000 (!!!! lol)  to over 24 hours, in order to conserve space and make it more readable.

I also rewrote combine.sh so it combines source files in the correct order.

[WHAT! NINE-THOUSAND!](https://www.youtube.com/watch?v=SiMHTK15Pik "YouTube")

### CODE REVIEW

**Comment by Aktanusa** [comment]
I dunno if I agree on removing the over 9000 part =p.  I am a DBZ fan if you have not figured it out, lol.  I'll take a look in a bit (hopefully).

**Comment by redthefed** [comment]
The main reason I changed it was times with four digit days were really long strings.  But yeah love the dbz reference :)

**Comment by redthefed** [comment]
Yay version change.  Killing this pull for now.

**Comment by Aktanusa** [comment]
You didn't need to do that, as I may be able to use some of the code.  I'll still take a look after I fix it for the new version.

**Comment by redthefed** [comment]
it was mostly just formatting anyway.  nothing backend.  i'll make a new pull on dev after the main changes are in.

**Comment by Aktanusa** [comment]
I mean I can do all the minor fixes since I'm changing the code for the new version anyway.  I must say that I will probably still leave 9000 there, or at least make it an option (that is default =p).

**Comment by redthefed** [comment]
sure, reopening it on dev for ya then

**Comment by Aktanusa** [comment]
Okay thanks!  I'll take a look and if it's minor, I'll add them =D.

**Pull request closed without merging**
