### PR TITLE
Updated for 2.002 multiplicative egg behavior

### PR DESCRIPTION
**Pull request by DeathOfBalance**

### CODE REVIEW

**Comment by Aktanusa** [comment]
Just a heads up, usually `CookieMonster.js` is the "compiled" file from `Combine.bat`.  The changes you made should have been in `src\Sim.js`.  It's fine, I'll probably merge, then back port it to `src\Sim.js`.

**Comment by DeathOfBalance** [comment]
Alright, I'll keep that in mind! Thanks :-)

**Comment by Aktanusa** [comment]
Looking at your profile, you don't seem to be that new to coding..  I guess you just missed the source files?  Lol

**Comment by DeathOfBalance** [comment]
Well, I'm a mathematician, but I've done some programming in Java and
Python (mostly to solve some Project Euler problems for fun). I don't
really know anything about Git or how to help others maintain and improve
their code. However I want to learn as much as possible and am eager to
help improve Cookie Monster in any way I can. It's an awesome add-on!


Alex

**Comment by DeathOfBalance** [comment]
Naive question: how exactly is
http://aktanusa.github.io/CookieMonster/CookieMonsterBeta.js generated? I
thought that perhaps merging my code would change that file, but it seems
to have no effect.


Alex

**Comment by Aktanusa** [comment]
Thanks for your kind words.  If you really want to help out, as a mathematician, tell me what is the formula to find the best thing to buy at any given time?  That is what I liked solved, if possible, lol.  Everything @ http://aktanusa.github.io/ is served from the the gh-pages branch.  This is why master branch doesn't have the beta JS and why only gh-pages branch has the beta JS.  I would like to (try) and finish all the preliminary changes before pushing a new beta JS to gh-pages.

**Comment by DeathOfBalance** [comment]
That is definitely a challenging problem, and I will think about it!


Alex

**Comment by Aktanusa** [comment]
Btw, not sure you've noticed, but your fix is live now.

**Pull request merged**
