### PR TITLE
Fix Wrinklers Typo in Description

### PR DESCRIPTION
**Pull request by tayrayb**
I just spotted a typo in the description for "Calculate time with Wrinklers". It right now says "Wrinkers" in the description.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Thanks.  Can you set it to go to dev branch?

**Comment by tayrayb** [comment]
No problem, All done.

**Comment by Aktanusa** [comment]
Thanks again, though you forgot to also change the source files =p.

**Comment by tayrayb** [comment]
No worries, sorry about that. Still learning a lot about Git. :D

**Pull request merged**
