### PR TITLE
"Fixed" TypeScript config/files

### PR DESCRIPTION
**Pull request by hyoretsu**
TypeScript has something called type inference, so you don't have to explicitly say that an array that only has strings is a `string[]`. In fact, if you use a generic type such as `{ [index: string]: string }` you're not really doing much, since there'll be no IntelliSense whatsoever. You should either create an interface to disclose what each key is (you can define a constant value for them) or let TS figure that out by itself.

### CODE REVIEW

**Comment by DanielNoord** [comment]
This PR does a lot more than only "fix" the config types. So I will try to respond to them all:

1) Is there a reason why you would not want `string[]` to be explicit? It seems to me to be a good way to avoid future maintainers/contributors adding an entry that is not a string. If it is not there typescript would throw an error when this happens and the contributor will have to infer the correct type him or herself. While this is not very difficult I don't see why it would be bad to make this explicit.

2) `{ [index: string]: string }` is indeed something we might want to change. However, just removing it altogether is not the right way to go. This allows adding (for example) an effect to the `Effects` const with a number as display title, without an error being thrown. Such errors are what I believe typescripts tries to avoid: indicating to maintainers/contributors how certain variables, functions and classes should be declared. Making an interface would indeed be best, but creates the difficulty of having to change two files (the interface and the actual const) when changes occur in the main game. This is something I would like to avoid. I have not found a good solution to this.

3) Why did you separate the setting classes? This is recommended according to ESLint and I don't really see anything against it, but perhaps I missed a good argument.

4) Adding `eslint-import-resolver-typescript` might indeed help with some of the import errors. I might need to look into this, but it seems to be outside of the scope of this current PR.

5) Changing the tab width and print width is also something I am not really in favour of, although this is a personal preference. I have you really insist I am open to change them for the project, but I don't think it is good practice to do that as part of one commit/PR. It is change of the style of the project and changing it secondary to a number of other changes while not mentioning it in the PR/commit feels odd.

**Comment by hyoretsu** [comment]
It "fixes" in a way to fully utilize TypeScript's capabilities.
> 1. Is there a reason why you would not want `string[]` to be explicit? It seems to me to be a good way to avoid future maintainers/contributors adding an entry that is not a string. If it is not there typescript would throw an error when this happens and the contributor will have to infer the correct type him or herself. While this is not very difficult I don't see why it would be bad to make this explicit.

The contributor wouldn't have to infer the type. TypeScript infers the type for us, and IntelliSense tells us what type a variable has. Usually arrays only have a single type. The error itself is TS already telling us the type so we don't have to guess it.

If they were to ignore that, and the type that TS is already telling us the variable has, they can just as easily scroll further up and change the variable type to do whatever they want. That's a difference from static typing to dynamic typing, and TS is merging both. Specifying types when it's really needed, and letting TS magic work where it's not.

> However, just removing it altogether is not the right way to go. This allows adding (for example) an effect to the `Effects` const with a number as display title, without an error being thrown. Such errors are what I believe typescripts tries to avoid: indicating to maintainers/contributors how certain variables, functions and classes should be declared. 

It may not be, (it usually isn't) but you can enforce it to have only said properties by creating a separate interface disclosing each one. But that'd double the size of things, so I didn't bother as of now since each object's gigantic af. Plus, simply removing that generic typing is still better, since we get IntelliSense. Generic typing = worse than no typing at all if that variable has a defined shape, you're pretty much going back to JS. You don't always need a separate interface for things.

> Making an interface would indeed be best, but creates the difficulty of having to change two files (the interface and the actual const) when changes occur in the main game. This is something I would like to avoid. I have not found a good solution to this.

You can leave interfaces in the same files as the objects, but that's the only way it can work. TS was meant as an upgrade to the JS that didn't have static typing at all.

I was going to try making an ISettings interface, but the way non-default settings were created was complicated and was still JS.

> 3. Why did you separate the setting classes? This is recommended according to ESLint and I don't really see anything against it, but perhaps I missed a good argument.

The ESLint rule means that a single file shouldn't tackle the world, but instead a single problem. It probably comes from SOLID's S, which means: Single responsibility principle - Class has one job to do. It's generally a good idea to follow ESLint rules, and in the case of this one have a single class per file, but not always. Which is why I only disabled it for that single file.

There were 5 files for the same things, which are settings. One of them was only used in the other 4 and the other 4 were only imported in a single file. Putting all of them in a single file not only leaves us with less places to look at, which makes it more organized, but also doesn't force you to import 4 different things from 4 different files.

That being said, the main feature I was changing in them was that in TypeScript, you can declare and assign a variable in the constructor. So there's no need to first declare them as public and then assign a value in the constructor's body.

> 4. Adding `eslint-import-resolver-typescript` might indeed help with some of the import errors. I might need to look into this, but it seems to be outside of the scope of this current PR.

It does solve import problems. I don't know if fully, since this is a weird half-TS implementation that gets imported into vanilla JS files, but TypeScript's what I've been mainly working with for 1 year.

> 5. Changing the tab width and print width is also something I am not really in favour of, although this is a personal preference. I have you really insist I am open to change them for the project, but I don't think it is good practice to do that as part of one commit/PR. It is change of the style of the project and changing it secondary to a number of other changes while not mentioning it in the PR/commit feels odd.

I didn't really change something in that regard. You already had an ESLint rule to enforce 100 line width, and the tab width you were using was 2. My personal preference is tab width of 1 and line width of 120. All I did was move them from some ESLint rule I didn't even know existed to Prettier. Aside from that it was a also a fix, though now that I think about it not related to TS. Prettier was missing some setup on ESLint, which is also why the CI failed.

**Comment by hyoretsu** [comment]
I don't know how I closed it, all I did was force push from GitKraken. But now I separated Prettier-related configs from TS-related ones

**Comment by DanielNoord** [comment]
> The contributor wouldn't have to infer the type. TypeScript infers the type for us, and IntelliSense tells us what type a variable has. Usually arrays only have a single type. The error itself is TS already telling us the type so we don't have to guess it.
> 
> If they were to ignore that, and the type that TS is already telling us the variable has, they can just as easily scroll further up and change the variable type to do whatever they want. That's a difference from static typing to dynamic typing, and TS is merging both. Specifying types when it's really needed, and letting TS magic work where it's not. Explicit =/= enforced, and TS already explicits most things to us.

I don't see what problem removing explicit typing solves. As I see it, in your current version a contributor can add an entry to `Effects` or `ValCookies` of another type than is currently used. For example, when a number entry to `ValCookies` is added TS automatically updates the type of `ValCookies` but this is not what we want it do. We want it to strictly enforce types on these data-structures.

> It's still better than leaving it with that generic typing though, since we get IntelliSense. Generic typing = worse than no typing at all if that variable has a defined shape. You're pretty much going back to JS. You don't always need a separate interface for things. (You would in this case)

The problem is that the current constructs don't have a defined shape and thus we need the generic typing to have any benefit of using TS.

> That being said, the main feature I was changing in them was that in TypeScript, you can declare and assign a variable in the constructor. So there's no need to first declare them as public and then assign a value in the constructor's body.

This is indeed a good change to make, but I would prefer keeping the files separate. Following your own suggestion I think it is indeed better to follow ESLint where possible. 

> I didn't really change something in that regard. You already had an ESLint rule to enforce 100 print width, and the tab width you were using was 2. My personal preference is tab width of 1 and print width of 120.
> 
> All I did was move them from some ESLint rule I didn't even know existed to Prettier. Aside from that it was a also a fix, though now that I think about it not related to TS. Prettier was missing some setup on ESLint's side, which is also why the CI failed with loads of "Replace X to remove an Enter"

I believe I put these rules in the ESLint file because otherwise ESLint does not know about these settings when prettier applies them and while throw an error. This is one of the reasons your current build still fails.

**Comment by hyoretsu** [comment]
> I don't see what problem removing explicit typing solves. As I see it, in your current version a contributor can add an entry to `Effects` or `ValCookies` of another type than is currently used. For example, when a number entry to `ValCookies` is added TS automatically updates the type of `ValCookies` but this is not what we want it do. We want it to strictly enforce types on these data-structures.

Removing explicit generic typing. `string[]`  is just being redundant, arrays aren't normally supposed to hold more than 1 type of data. And using `{ [index: string]: string | number | { [index: string]: number }; }` is no better than having no type at all. Both of them are equally mutable. Explicit typing is meant specifically for more complex data, like the objects, not a simple array of strings.

Generic typing is never a good thing to use. And in `string[]`'s case, it isn't bad but it doesn't do anything to actually change the types. TypeScript is something that merely informs you of variable types and warns you about any incompatibility.

> The problem is that the current constructs don't have a defined shape and thus we need the generic typing to have any benefit of using TS.

Except generic typing is precisely what give you 0 benefits from TS. There's literally no IntelliSense whatsoever for those objects, and that's the exact reason JS is so weird for me. That problem's easily solvable by copying the object and changing all values to string/number though. No way around having to change things on 2/3 different places if you want to enforce properties **and** keep interfaces on a separate file.

> I believe I put these rules in the ESLint file because otherwise ESLint does not know about these settings when prettier applies them and while throw an error. This is one of the reasons your current build still fails.

I never used GitHub's CI, but since NPM's already enforced, you could set up a local precommit script to lint all files before even creating a commit. That's what I use, 0 problems.

When I run `npx eslint src` (the command you're currently using) with an error, I get the same `5:18  error  Delete '··········' prettier/prettier` that my build's throwing up. When I run it as `npx eslint --fix`, the error gets automatically solved. Hence, the same should work on the CI script that's currently failing.

**Comment by DanielNoord** [comment]
> *Removing explicit generic typing. `string[]` is just being redundant, arrays aren't normally supposed to hold more than 1 type of data. If they do, that's bad code, with or without TS. And using `{ [index: string]: string | number | { [index: string]: number }; }` is no better than having no typing at all. Both of them are equally mutable. Explicit typing is meant specifically for more complex data, like objects, not a simple array of strings.
> 
> Generic typing is never a good thing to use. And in `string[]`'s case, it isn't bad but it doesn't do anything to actually change a variable's type. TypeScript is something that merely informs you about types and warns/blocks any incompatibility.
> 
> Except generic typing is precisely what give you 0 benefits from TS. There's literally no IntelliSense whatsoever for those objects, and that's the exact reason JS is so weird for me. That problem's easily solvable by copying the object and changing all values to string/number though. No way around having to change things on 2/3 different places if you want to enforce properties **and** keep interfaces on a separate file.

I think we're covering two different problems here:
1) I agree that the generic typing for `Effects` removes the utility of TS. It removes the IntelliSense and therefore the benefit of having an immediate error thrown when an incorrect entry is added (which generic typing provides) does not outweigh the disadvantages
2) Removing the redundant generic typing for the basic constructs in the rest of the document is different (in my opinion at least). The current generic typing does not remove any IntelliSense (it is the same) and does help by immediately throwing an error when somebody adds an incorrect entry.

The best solution (imo) is therefore to create an interface for Effects and retain the current typing for the other constructs.

> > I believe I put these rules in the ESLint file because otherwise ESLint does not know about these settings when prettier applies them and while throw an error. This is one of the reasons your current build still fails.
> 
> I never used GitHub's CI, but since NPM's already enforced, you could set up a local precommit script to lint all files before even creating a commit. That's what I use, 0 problems.

This would probably fix the issue but then your editor no longer displays the errors and changes would be made without your knowledge. For most fixes this would not be a problem (they are mostly line breaks and white spaces), but I would like the editor to show the errors it is supposed to find. Moving the configuration to the ESLint file allows VSCode to do this. I don't know if this is different for other editors and I am certainly open to changes to accommodate other editors, but for me this changes feels like a step backwards in terms of clarity and usability for the contributor.

**Comment by hyoretsu** [comment]
> Removing the redundant generic typing for the basic constructs in the rest of the document is different (in my opinion at least). The current generic typing does not remove any IntelliSense (it is the same) and does help by immediately throwing an error when somebody adds an incorrect entry.
> 
> The best solution (imo) is therefore to create an interface for Effects and retain the current typing for the other constructs.

Using `string[]` for an array of strings does enforce its type, but TS usually isn't meant to be that much of a static language. It creates the same (unnecessary) problem you're trying to avoid with object interface, having to change things in 2 places. Even if in this case you wouldn't want to do that anyway.
One example of why having two data types in an array is bad code is that you can't use a string/number method on a `.map()`, so it shouldn't be in any code, regardless if it's TS or JS, enforced or not.
 
> This would probably fix the issue but then your editor no longer displays the errors and changes would be made without your knowledge. For most fixes this would not be a problem (they are mostly line breaks and white spaces), but I would like the editor to show the errors it is supposed to find. Moving the configuration to the ESLint file allows VSCode to do this. I don't know if this is different for other editors and I am certainly open to changes to accommodate other editors, but for me this changes feels like a step backwards in terms of clarity and usability for the contributor.

Oh, if you're talking about editors that's a completely different thing then. VSCode shows and fixes errors just the same with this prettier config. And in the situation I said about someone not having ESLint/Prettier installed, the errors wouldn't show up either way before PR level.
You can go all the way and use ESLint's `quotes: ["error", "single"]` and `comma-dangle: ["error", "never"],` to get rid of the 2 remaining Prettier rules. That way no visual config would be separated in a different tool's file, instead of only using half of what Prettier is meant to do and leaving the other half to ESLint.
I'd certainly use Prettier whenever possible though. It also works on JSON and such, which btw the current ESLint rule doesn't enforce. The mocha file remained a weird one with a tab width of 4.

**Comment by DanielNoord** [comment]
> Using `string[]` for an array of strings does enforce its type, but TS usually isn't meant to be that much of a static language. It creates the same (unnecessary) problem you're trying to avoid with object interface, having to change things in 2 places. Even if in this case you wouldn't want to do that anyway.
> One example of why having two data types in an array is bad code is that you can't use a string/number method on a `.map()`, so it shouldn't be in any code, regardless if it's TS or JS, enforced or not.

I can understand that TS is not traditionally used to statically type, but I don't why we wouldn't want to use it in place where we can use that.
Obviously it is better to never a situation where it might be necessary, but it can serve as a useful reminder to future contributors when they are about to add a second data type to objects or constructs that should not have those.

I know there are many problems and things you should normally not want in JS/TS-code in this project, but that is the result of having a project that is 7+ years old. I would gladly have the project conform to modern-day standards, but that is not a feasible undertaking for the small group of willing contributors we have right now.

> I'd certainly use Prettier whenever possible though. It also works on JSON and such, which btw the current ESLint rule doesn't enforce. The mocha file remained a weird one with a tab width of 4.

Your point about JSON and prettier is valid. However, adding prettier would require us to either change the npm-config (as you suggest) or change some stuff in the CI. As it stands, the current implementation cannot be merged.

**Pull request closed without merging**
