### PR TITLE
Cookie Monster Beta 2.002

### PR DESCRIPTION
**Pull request by DeathOfBalance**
I updated the code for the multiplicative egg part.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Well thanks for the heads up Version 2.002 Beta of CC is up.  I'll take a look at your code, but it should be merge into the beta branch.  Master is for live version of CC.

**Comment by DeathOfBalance** [comment]
Okay, I think I did it correctly now. I'm rather new to this Github business!

**Comment by Aktanusa** [comment]
It's okay =).  I took a quick look.  Thanks for finding the changes.  I guess this merge should be closed for the other merge?

**Comment by DeathOfBalance** [comment]
Yep!

**Pull request closed without merging**
