### PR TITLE
Add TLS to HTTP links

### PR DESCRIPTION
**Pull request by sigv**
Please use HTTPS wherever it is supported. It is just good practise, you know.

### CODE REVIEW

**Comment by Aktanusa** [comment]
I agree this is a good idea, but why the two pull requests?  I see one is to master and other to dev, but it should be only to dev first, as that's the order to go to master.

**Comment by Aktanusa** [comment]
Hmm, it is true that it's just a README change, so nothing to test, but then the gh-pages branch needs it too, lol.

**Comment by sigv** [comment]
Let's just go the _regular_ route then.

**Comment by Aktanusa** [comment]
Well I am going to be doing an update to master and gh-pages soon anyway, due to the new version of CC, lol.

**Pull request merged**
