### PR TITLE
Bottom bar tidying and combine.sh fix

### PR DESCRIPTION
**Pull request by redthefed**
A few small tweaks to the bottom bar as well as a re-written combine.sh.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Thanks for your hard work!  I'll have some free time soon to finally work on the changes.  I'm sure a lot of people are counting on me, so I better hurry, lol.

**Comment by redthefed** [comment]
No worries eh.  I'm mostly using this as an opportunity to learn js and customize the game I'm playing while I code.  Two birds one stone.

**Comment by Aktanusa** [comment]
Gotcha

**Comment by Aktanusa** [comment]
I like that you removed a lot of the white space, but the extra carriage return at the end of each file was needed for the combine.

**Comment by redthefed** [comment]
cool, thanks for the heads up.  i'll tell my editor to knock it off :)

**Comment by Aktanusa** [comment]
Oh no wonder.  By the way, the extra hidden overflow style isn't really working for FireFox at least.  I'm looking for a better solution before releasing.  Or attempt to.  I may revert back.

**Comment by Aktanusa** [comment]
Unfortunately, I will have to revert back the new table attributes.  With it there, Chancemaker number is cut off sometimes even if you have enough space.  Sorry about that.

**Comment by redthefed** [comment]
no worries.  i'm gonna test it more, see if i can get it working on firefox and other browsers.  i'll let you know

**Comment by Aktanusa** [comment]
You're on the right track with fixed and hidden.  I think there needs to be more info.  I found this site to be useful:

https://css-tricks.com/fixing-tables-long-strings/

**Pull request merged**
