### PR TITLE
Make a Userscript and Refer the README to It

### PR DESCRIPTION
**Pull request by mason1920**
Tested and works with Greasemonkey, Tampermonkey, and Violentmonkey.

### CODE REVIEW

**Comment by DanielNoord** [comment]
Thanks for the PR. I always like to clean-up the Readme where possible.
I have one question though, since I am not that familiar with Userscripts. Is this approach easier to understand for less experienced users than the one we currently show?

**Comment by mason1920** [comment]
@DanielNoord, most userscript managers prompt for installation when visiting `.user.js` files, that way people (rightfully) don't need to learn how to add the scripts manually.

Additionally, unlike the previous example userscript, this one works in Greasemonkey.

**Comment by DanielNoord** [comment]
This is indeed what I hoped. Does it also work when the file is "embedded" like it is on GitHub? Or do they need to visit [the file directly](https://raw.githubusercontent.com/mason1920/CookieMonster/dev/cookie-monster.user.js)?

If it does indeed work could you make `cookie-monster.user.js file` a link to the location of the file (I'd assume `https://github.com/Aktanusa/CookieMonster/blob/dev/cookie-monster.user.js`). This will make it even easier for inexperienced users :)

**Comment by mason1920** [comment]
It would need to be the raw file, yes. the problem with a link is that it doesn't change per branch, so it's your call which raw file to point to (the master, dev, somewhere else like you did with github.io for the main mod). I vote to leave it be and let the user go to the raw file himself to give him the choice of branch.

**Comment by DanielNoord** [comment]
Made some small changes and merged :)
Thanks for your help!

**Pull request merged**
