### PR TITLE
Update CM.Disp.FormatTime

### LINKED ISSUE #502: CM.Disp.FormatTime is formatting time incorrectly
It simply not displaying years, though [calculates it here in the code](https://github.com/Aktanusa/CookieMonster/blob/master/CookieMonster.js#L1314).

Dates in the stats as of now:
image

Bug can be reproduced with any file save where any of the dates is bigger than a year.

### PR DESCRIPTION
**Pull request by Zohnannor**
Add years to date formatting, fixes #502

### CODE REVIEW

**Comment by DanielNoord** [comment]
Thanks for your fix! Strange how this was missing from the code.
However, we use source-files to compile the final `CookieMonster.js` file. Could you make the fix to the `Disp.js` file, as found in the `src` folder and then use either of the combine files (depending on your OS) to create the `CookieMonster.js` file?

**Review by DanielNoord — CHANGES_REQUESTED** [review]
See earlier comment.

**Comment by Zohnannor** [comment]
No problems!

**Comment by DanielNoord** [comment]
Thanks! Approved :)

**Pull request merged**
