### PR TITLE
Added compatibility with mods that inject into PP-related vanilla functions

### PR DESCRIPTION
**Pull request by hyoretsu**
Though I just noticed that Cookie Monster would also break with kitten upgrades, checking that.

### CODE REVIEW

**Comment by hyoretsu** [comment]
It's related to how CM also gets a static copy of `Game.CalculateGains`. It'll take some time, but I'll check what's useless from there. (Changing `CM.Sim`'s to vanilla and checking if anything breaks)

**Comment by DanielNoord** [comment]
Just thinking out loud here: is there a way to create a "Create Sim-copy" function that can then be called on each Game function to create one where everything is replaced?
I am thinking of one function that stores all possible replacement actions (so `Game.Objects` to `Sim.Objects` and `Game.Has` to `Sim.Has`) which is then passed functions like `Game.CalculateGains()` and `Game.GetTieredCpsMult()`

**Comment by DanielNoord** [comment]
Another problem I just thought of is that using `new Function` will also result in errors with ESLint as it is basically an `eval`.
This is also the problem I ran into last time when I wanted to remove all evals.

**Comment by hyoretsu** [comment]
> Just thinking out loud here: is there a way to create a "Create Sim-copy" function that can then be called on each Game function to create one where everything is replaced?
I am thinking of one function that stores all possible replacement actions (so Game.Objects to Sim.Objects and Game.Has to Sim.Has) which is then passed functions like Game.CalculateGains() and Game.GetTieredCpsMult()

Not as broad as that, but you can use the same method I used to automate that.
```javascript
new Function(
	`return ${Game.anyFunction.toString()
	.replaceAll(/Game/, 'CM.Sim')}`,
 )();
 ```
 In an even more automated way:
 ```javascript
 const gameObjKeys = Object.keys(Game);
 const gameObjValues = Object.values(Game);
 const CM.Sim = {};
 
 gameObjValues.forEach((originalValue, index) => {
  let injectedFunc;

  if (typeof originalFunc === 'function') {
   injectedFunc = new Function(
    `return ${originalValue.toString()
     .replaceAll(/Game/, 'CM.Sim.')}`,
   )();
  }

  Object.assign(CM.Sim, {
   [gameObjKeys[index]]: injectedFunc || originalValue,
  })
 })
 ```
That should create a copy of Game with all Game methods changed to CM.Sim, (might need some checking to make sure nothing was changed unintentionally) though it'd probably lag a bit since that's pretty much going through the entire game.

Creating CM.Sim functions in this `new Function()()` way would be an easy fix for this problem which takes care of injections, especially since you'd already want to do that eventually when optimizing Cookie Monster. But you'd need to have a warning to place Cookie Monster last on loading order/setting a delay as noted by you before, so it isn't that much of a fix. (Although doable)

> don't know if this is intended but I think we should still create `CM.Sim..GetTieredCpsMult()` otherwise the base game will start to use the data stored in `CM.Sim` instead of `Game` to calculate CPS and run the game.

~~I don't know what that'd affect~~ Yeah, CpS changes some time after buying/selling buildings. It was intended, as that'd make the function work with all future injections, but it introduced that bug. Also checking a possible way to fix that.

> Another problem I just thought of is that using new Function will also result in errors with ESLint as it is basically an eval.
This is also the problem I ran into last time when I wanted to remove all evals.

For that, it is best to disable no-new-func rule. You already need to disable quite a few rules to work with Orteil code and ESLint. And [Are eval() and new Function() the same thing?](https://www.xspdf.com/resolution/52136916.html)

**Comment by DanielNoord** [comment]
Should indeed be able to do this somewhat automated, although I think I prefer doing it on a per-function basis instead of the full game at once.

We could put the replacing functions into `CM.Main.Loop()` to circumvent the issue of CM loading before a content mod, although that feels a bit "hacky" an introduces unnecessary functions into the loop (it would only rarely actually be useful).
Perhaps doing something with checking in the loop if the number of registered mods has increased and in that case re-replace all functions might work.

Currently I am only using the `recommend` set of rules for ESLint. Changing to `all` or `airbnb` gave about 10k errors (mostly indentation and style). If I ever change this using no-new-func will probably be necessary indeed.

**Comment by DanielNoord** [comment]
I have worked on this some more and have implemented code that recognizes content mods in #592.

Please do tell if any issues remain, but from my personal testing it all seems to work now!

**Pull request closed without merging**
