### PR TITLE
Support for v2.031

### PR DESCRIPTION
**Pull request by LloydW93**
This PR is based upon #316 and therefore supersedes it.

It adds support for Cookie Clicker v2.031's new building and heavenly upgrades. The significant diff for CalculateGains is a result of recreating the function from Cookie Clicker's source so it is easier to compare with the current base game's equivalent logic.

```javascript:(function() { Game.LoadMod('https://lloydw93.github.io/CookieMonster/CookieMonster.js');}());```

Can be used in the meantime to load this version of the mod.

### CODE REVIEW

**Comment by DrySoldier** [comment]
Thanks, I'm glad someone is supporting it. Hopefully @Aktanusa gets some contributors on to update the main repo.

**Comment by DanielNoord** [comment]
@Aktanusa or any future maintainer might one to compare efficiency and code of this PR and #319. Both serve their purpose in fixing CM for 2.031!

**Comment by bitsandbytes1708** [comment]
@DanielNoord I think we should merge #319, it looks like it adds support for more items than this. Open to discussion though, I haven't thoroughly reviewed the code yet.

**Comment by bitsandbytes1708** [comment]
We have merged #319 instead. Sorry! Thank you for your hard work though :) it is appreciated.

**Pull request closed without merging**
