### PR TITLE
Introduces means to calculate wrinkler spawn time

### PR DESCRIPTION
**Pull request by HeroicKatora**
Moved from #107 
The function expectation will calculate the expected time it takes for
n Bernoulli experiments happening simultaneously with a given chance
to each complete at least once. This is exactly what happens with
Wrinklers in Cookie Clicker.

This only introduces the necessary math in order to incorporate Wrinkler respawn times into calculations like Wrinkler popping assistance.

Documentation for function expectation:
-   Parameter maxFreeSlots: Atm it is 12, the math relies on inverting a matrix thus the size needs to be restricted in some way. Choosing a small number is advisable but not obligatory.
-   Parameter chance: The probability to spawn a Wrinkler in a tick.
-   Output expected: An array holding the expected times. In case that n slots are still open, expected[n] will be the number of ticks that it will take until those are all filled, on average. To calculate the time it will take for the first slot to be filled, just calculate expected[n] - expected[n-1].

This is for issue #106

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I think it is possible to apply a pull request as a patch as well but moving this request to the dev branch is probably the easier way.

**Comment by Aktanusa** [comment]
Thanks.  You got me, I'm a newbie to github, lol.  Should I be using maxFreeSlots = 10 when the player can't spawn 12 wrinklers?  When would you need to use the "chance" parameter?

**Comment by HeroicKatora** [comment]
It really doesnt matter if you input maxFreeSlots = 10 or maxFreeSlots = 12, the first 11 elements should remain the same. For "chance" you should input the current wrinkler spawn chance, this is modified by the current elder wrath stage and one ascension upgrade, I think.

**Comment by Aktanusa** [comment]
So just to warn you, it may be like 2 weeks before I get around to this.  Busy this week before my week of vacation.  Sorry about that.

**Comment by HeroicKatora** [comment]
If you want me to, I could write additional functionality and code the other part of my request as well, or at least part of it.

**Comment by Aktanusa** [comment]
That would be nice, but the problem is I have not decided on how to show this information yet.  I will probably need to think hard on what I can do.

**Comment by Aktanusa** [comment]
Just an updated since it's been 20 days already (geez time flew).  I have not forgotten about this, but I'm trying to do some things first.  Sorry for the delay.

**Comment by Aktanusa** [comment]
Another update.  Yea, I've been busy.  Really sorry for the delay, I hope to have time soon!

**Comment by Aktanusa** [comment]
My goodness I've been slacking on this.  So sorry, I should have some free time soon to finally add this.

**Pull request closed without merging**
