### PR TITLE
Simpler readme Userscript code

### PR DESCRIPTION
**Pull request by icecream17**
I made this because I wasn't sure about 
```javascript
window.eval(anonymous function string)
```
and I felt like replacing it with
```javascript
anonymous function
```

I also changed "var" to "const" while I was at it

Tested in _Tampermonkey_ (and works) but _not Greasemonkey_

### CODE REVIEW

**Comment by bitsandbytes1708** [comment]
Hello! Please switch the targeted repository to Dev instead of Master. Thank you! Also, if it doesn't work with Greasemonkey, I'm not sure if we should merge it.

**Comment by DanielNoord** [comment]
Paging @Aktanusa as this is a change of the Readme and I am not quite sure about the procedures to change it in all the right location.
Code looks fine.

**Review by DanielNoord — APPROVED** [review]

**Comment by Aktanusa** [comment]
Hmm, since this is a readme change, is the problem of pushing to master without the other changes?  If so, that is a good question.  I think you make the change in dev, and this make a patch for master, which would then merge to gh-pages.  This this change would also happen directly on Wiki page also.

**Comment by DanielNoord** [comment]
Okay! I was mostly worried about the wiki, but that fixes itself it seems. I will merge this!

**Comment by Aktanusa** [comment]
Just to be clear, when I said the change would also happen on the wiki, I mean someone would need to manually add it to the wiki.  I don't know if you are @bitsandbytes1708 has an account there...

**Pull request merged**
