### PR TITLE
Fix buying with block protection & exact cookies

### PR DESCRIPTION
**Pull request by costas-basdekis**
The check was wrong, since it wouldn't allow you to buy a building  for the exact amount of cookies in your bank, for example when  you're trying to buy your first cursor after clicking exactly 15 times.

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Comment by DanielNoord** [comment]
You'll need to rebuild the final file. This is not set up in the CI to be done automatically sadly.

**Comment by costas-basdekis** [comment]
Thanks @DanielNoord, I have now rebuilt with `npm run build-dev`

**Comment by DanielNoord** [comment]
Could you also build with `npm run build`? That way those users that don't use the dev version will also get this fix!

**Comment by costas-basdekis** [comment]
I run `npm run build-final` (there wasn't a `build` command)

**Comment by DanielNoord** [comment]
> I run `npm run build-final` (there wasn't a `build` command)

It has been quite some time since I built this myself :sweat_smile: Thanks!

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
