### PR TITLE
Add missed GC clicks stat with preference, create a section header fo…

### PR DESCRIPTION
**Pull request by Alhifar**
…r misc stats

I'd wanted this in my personal copy and saw you had an open request for it, so I went ahead and pulled together a submission for it.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Ah, I see.  Thanks!  I'll take a look.

**Comment by Aktanusa** [comment]
Do you mind if I reformat your code to the way I like it?  You'll still be credited of course =)

**Comment by Alhifar** [comment]
Of course! I tried to follow the style that was there, but I wasn't too sure with variable names and such

**Comment by Aktanusa** [comment]
I saw that! I don't think there be much changes actually, just probably placement and stuff, lol.  Thanks again!  I'll add it later today.

**Comment by Aktanusa** [comment]
I think I'm not going to make it as an option to turn on and off as it be the only option right now for statistics.  Anyway I can just hide the Misc area if I really want to hide it.

**Comment by Aktanusa** [comment]
Once again, thanks for the code, it has been pulled into dev branch and will be released with version 2.3

**Comment by Aktanusa** [comment]
I should mention that where you placed the extra stuff, on a new ascension, the stat will be missing since it is under the following if statement:

```javascript
if (Game.season == 'christmas' || specDisp || choEgg) {
```
Your added code should be after this if statement.

**Pull request closed without merging**
