### PR TITLE
Re-order garden max rewards info on stats screen by amount of cookies

### PR DESCRIPTION
**Pull request by humdogm**
Having it out of order is big dumb
In order is big brain

### CODE REVIEW

**Comment by humdogm** [comment]
Can you please run again, I ran `npm run build-dev` and force-pushed
Though also why not just run `npm run build-dev` in the CI workflow

**Comment by humdogm** [comment]
Hi, can this be merged please?

**Comment by DanielNoord** [comment]
Sorry, completely slipped of my radar!

**Comment by DanielNoord** [comment]
> 

I wrote most of the CI with little experience of JS and its packaging environment. I must say I'm still mostly a Python dev. Any help fixing the CI is much appreciated!

**Pull request merged**
