### PR TITLE
An actual implementation of ESLint+code "fixes"

### PR DESCRIPTION
**Pull request by hyoretsu**
After seeing the... weird ESLint implementation, to say the least, which didn't actually amount to much since there were still a lot of flags, I went ahead and installed it using NPM. (Since you were already using it in `.github/workflows/ESLint.yml`)

I didn't make any (obvious) optimizations/refactoring though, like switching all `for`'s with `.forEach()` as it's simpler and newer. I did change Header.js, because it's easy and to show how much better it can get.
Ideally you'd also turn everything into an ES6 module instead of this weird thing where it's just straight up slicing a big file into multiple ones.

As for documentation, it's too tiring to fix JSDoc and I honestly never use it, TypeScript is simply better. So all comments may be a little weird. (At least in VSCode, but they still look as weird as before regardless)

### CODE REVIEW

**Comment by DanielNoord** [comment]
As you might have guessed I am not that experienced with NPM and ESLint. I mainly used it to force some kind of linter on new pull requests for people outside of the project. I did not see any real benefit to using NPM, as it might also make it harder for less-experienced coders to start contributing and I personally don't know what benefits it would give the project. Am I missing some clear ones?

I don't have a computer science degree so I am not totally up to speed with the latest functions and standards, such as using `.forEach()`. I mainly use this project a way of learning JavaScript and add them as I go, but there is also an enormous backlog of undocumented and obscure functions. So I try to balance writing ES6-compliant code with refactoring code from 2014 to make it at least understandable. 
That said, is there a real functional benefit to using `.forEach()`? Or is it just prettier and the new standard?

I stumbled upon JSDoc while I was trying to clean up the codebase and in hindsight converting to TypeScript might have been better. I am not sure how easy it would be to do so at this time. I would think there might be some conversion tools online.

**Comment by hyoretsu** [comment]
> I did not see any real benefit to using NPM, as it might also make it harder for less-experienced coders to start contributing

The way you set it up, using npx a shell script when committing, still forces people to have NPM afaik since they're bundled together, so that kinda defeats the purpose. (Either that or it won't lint at all)


> and I personally don't know what benefits it would give the project. Am I missing some clear ones?

Take JSColor that's included for example. It's available as a [NPM package](https://www.npmjs.com/package/jscolor). You can install various libs with it instead of including them locally/implementing yourself. There's also a site releasing soon that requires having a package.json, [CCRepo](https://ccrepo.glander.club/all), (setup already included in my PR) from the same creator of the new CC modding framework, [Cppkies](https://github.com/Cppkies-Team/Cppkies).


> That said, is there a real functional benefit to using .forEach()? Or is it just prettier and the new standard?

I... don't actually know about that but it's definitely easier to read and uses less/less trippy code. Instead of doing
```
for (let i; i < Game.wrinklers.length; i++) {
 let { sucked } = Game.wrinklers[i];
 console.log(sucked);
}
```
you can write
```
Game.wrinkers.forEach(wrinkler => {
 console.log(wrinkler.sucked);
})
```
You're simply using a new (from around 5 years ago, so 95% of the internet supports it) feature from JS. https://alligator.io/js/foreach-vs-for-loops


> I stumbled upon JSDoc while I was trying to clean up the codebase and in hindsight converting to TypeScript might have been better. I am not sure how easy it would be to do so at this time. I would think there might be some conversion tools online.

Seeing how awful the code's become after 6+ years and it having more than 6k lines of code, it'd take quite some time, especially since you can't half-convert it. I don't think there's a tool for that because other than some patterns you gotta define for yourself (function parameters, objects, etc) it already does things automatically, e.g. `const x = 'anything'` x is already interpreted as a string, without having to do `let x: string;`.
It's like JSDoc but with a linter, it helps avoid many errors that come from misusing variables. (easy to happen due to the sheer, sometimes unnecessary, size of CM) You're able to use IntelliSense, which basically lists all variables/functions you can use and has documentation on their parameters and return type.
Every time I have to go through vanilla JS it feels lacking, and I realize how much better TS is. (I didn't spend that much time using JS before going to jQuery/TS though)

**Comment by hyoretsu** [comment]
You can also use NPM (package.json) to setup scripts (and in the case of my configuration, git hooks) and run them with `npm run`

**Comment by hyoretsu** [comment]
Also the way I merged the files also minifies them, so there's a 37% reduction on file size.

**Comment by DanielNoord** [comment]
The current implementation does not require NPM, that's why I set it up like this. To use ESLint yourself you will indeed need to install it, but by using a GitHub Action and providing the settings-file it wil also run against code of people that do not have it installed. It therefore allows us to run ESLint and gave instructions on what to change (in the action log) to less experienced programmers.

JSColor is indeed a packaged that could be installed via NPM, and this is why I only found out recently that it was updated. However, the current version is fine and there is no dire need to be up-to-date consistently (it wil not create any mod-breaking bugs). We don't really need any other packages so I don't really see the added benefit of NPM package-wise.

The Cppkies is a project which I have looked at from time to time. I think we might at one point try to implement this, but this will be after I have cleared the backlog of cleaning up the current code. 
However, a big problem I have found with many CC modding projects is that people tend to lose interest very quickly, the game is simply not that entertaining for a longer period of time. (Although there might of course be exceptions). This is why until now we have been very hesitant to rely on other peoples code and only use the base game Modding API. Completely building upon the API Cppkies offers will therefore likely not be something we will do, although I hope Orteil and the Cppkies team can create some form of collaboration.

Looking at `.forEach` it seems as if it is mostly a matter of preference, there is no real performance gain. I indeed like it better, but it will probably be something for the backlog.

The size and age of CM is indeed something that is very limiting now. A secondary problem is that most code relies on Game code so you (for example) need to exactly know how Golden Cookie Chains are calculated to check whether CM is doing this correctly. This makes changing and updating the code a very time-costly process as Orteil has not written the most readable code..

File size reduction is nice, but not that necessary for the project (I think). As it wil only run on computers and the full project is around 400 kB. Furthermore, the `CookieMonster.js` file in your PR does not actually run and throws a number of errors. We would need to fix those before we can take a decision on whether we want to change to NPM completely.

**Comment by hyoretsu** [comment]
> The current implementation does not require NPM, that's why I set it up like this. To use ESLint yourself you will indeed need to install it, but by using a GitHub Action and providing the settings-file it wil also run against code of people that do not have it installed. It therefore allows us to run ESLint and gave instructions on what to change (in the action log) to less experienced programmers.

I'd never used GitHub actions, though that requires an extra commit simply to fix ESLint errors.
Also given the sheer size of it and lack of info on what everything does, I doubt anyone inexperienced will venture himself to changing it. At least inexperienced enough to not know about ESLint, (and consequently NPM) one of the most basic tools for a programmer.
I myself didn't try optimizing it further (for now) because I'd probably stop midway through, too big/tiring/messy.


> We don't really need any other packages so I don't really see the added benefit of NPM package-wise.

It's like using Alexa to automate your home. Can you remove it to allow people who aren't good with technology to have the same "hardships" (in this case writing code without ESLint is indeed a hardship to me, I always copy it to a project of mine that has it) as everyone else? Sure, but it's really helpful to have her (NPM) doing misc things for you, even if you use it just for ESLint.
It's one of the things that made JavaScript a better language over the years. It didn't have a simple package manager for a long time, something other languages had. TypeScript was also released since JS also didn't have dynamic/static typing, making it even better.


> The Cppkies is a project which I have looked at from time to time. I think we might at one point try to implement this, but this will be after I have cleared the backlog of cleaning up the current code.

The only things CM would be able to use is probably 'load', 'save' hook and their injection method, I only sent it because few people know about CCRepo.


> However, a big problem I have found with many CC modding projects is that people tend to lose interest very quickly

That being said, Cppkies **was** in development for more than a  year before releasing, but I also don't use it (yet, or fully) because of certain things I need to do on my mod. 


> although I hope Orteil and the Cppkies team can create some form of collaboration.

Apparently Orteil doesn't really like mods, so probably not. (The 'create' hook in the new modding API just straight up doesn't work)


> The size and age of CM is indeed something that is very limiting now. A secondary problem is that most code relies on Game code so you (for example) need to exactly know how Golden Cookie Chains are calculated to check whether CM is doing this correctly. This makes changing and updating the code a very time-costly process as Orteil has not written the most readable code.

This is another hard thing for "less experienced programmers". Not only would they have to face the gigantic thing that CM is, with little documentation or TypeScript's insight, but also figure out how the hell Orteil does things in CC. (Not exactly an easy thing to do)
One thing that also bugs me (regarding size) is things like this
```
CM.Sim.GetTieredCpsMult = new Function(
 `return ${Game.GetTieredCpsMult.toString()
 .split('Game.Has')
 .join('CM.Sim.Has')
 .split('me.tieredUpgrades')
 .join('Game.Objects[me.name].tieredUpgrades')
 .split('me.synergies')
 .join('Game.Objects[me.name].synergies
 .split('syn.buildingTie1.amount')
 .join('CM.Sim.Objects[syn.buildingTie1.name].amount')
 .split('syn.buildingTie2.amount')
 .join('CM.Sim.Objects[syn.buildingTie2.name].amount')
 .split('me.grandma')
 .join('Game.Objects[me.name].id')
 .split('me.id')
 .join('Game.Objects[me.name].id')
 .split("Game.Objects['Grandma']")
 .join("CM.Sim.Objects['Grandma']")
 .split('me.fortune')
 .join('Game.Objects[me.name].fortune')}`
)();
```
Like... Why?... It's literally changing things for others that do the exact same thing. Sometimes not even from CM, but alternate ways from CC itself. And judging from the first function in `Sim.js` (big files crash my mobile Chrome) and its description, it's the same for that entire file.


> File size reduction is nice, but not that necessary for the project (I think). As it wil only run on computers and the full project is around 400 kB. 

I for one spent almost 1min to download 500KB on a bad day of my internet. (pretty sure the server was also shit, but it can still get slow af sometimes) It really doesn't take much work to minify files, and it's always a good thing to optimize your code.
In fact, because of NPM and the tools available to us, as long as we don't make errors (ESLint) or write in a bad way, (slicing up files instead of writing modules) we don't even have to worry about optimization or supporting old browsers, bundling tools (Webpack/Babel) will already do that for us.


> Furthermore, the CookieMonster.js file in your PR does not actually run and throws a number of errors. We would need to fix those before we can take a decision on whether we want to change to NPM completely.

I realized that after I went to sleep, though it's because of CM simply separating files. (which also forces Webpack to create an empty main.js file, excluded from commits) I'd already spent a whole day fixing ESLint problems in it so I forgot to test. An awful lot of `==` instead of `===` and there's probably no case at all where you'd want to use `var` instead of `let` or `const`.
Because of that, Webpack changed one variable to "a", but the other files don't know the variable they want is now named "a" nor that an "a" variable already exists.
I'll check if there's a way to make everything work, but it's easily solved by changing from "production" to "development" in `webpack.config.js`. (Though that'd remove minifying)

**Comment by hyoretsu** [comment]
Might take some time, it's throwing up a `TypeError: 'caller', 'callee' and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for call to them` error on `CM.Disp.Flash` because God knows why, I literally copied the function from current CookieMonster.js and it didn't work. Also
> It therefore allows us to run ESLint and gave instructions on what to change (in the action log) to less experienced programmers.

"Ideally ESLint would be run both locally and as a CI (both via package.json dev dependencies): So people who don’t know npm can commit and see that their code sucks then, but people who know how to use npm can do a good ol `npm i` and instantly know that their code sucks [...] it’s basically what the guy suggested in the first reply, **problem being, global packages** (the way he implies using eslint locally) **are a terrible practice**"
Said Z, Cppkies dev. I'd forgot about the detail that global ESLint sucks hard. I'd given up on setting it up because it doesn't allow external styles.

**Comment by hyoretsu** [comment]
Removing the parts with references to `caller` made those errors go away. But now there's more errors about bad code

**Comment by DanielNoord** [comment]
Lot to unpack here.

I understand that NPM offers a lot of benefits to programmers and that most experienced JS developers will use it. The thing is that we would like the project to be accessible to as many people as possible. Talking from my own experience, I only knew Python before starting on this. If I would have had to download NPM and understand how that works I would be much less inclined to help out in the first place. It is about making it as easy to contribute while still enforcing some kind of style. I totally understand that in any normal project this is not the way to go, but in a project that is relying on successive contributors that do not really communicate with each other (as they have often left the project when new ones start to join) I think it is paramount to make contributing/joining as easy as possible. Requiring knowledge of Javascript package managers could scare off people that could turn out to be valuable contributors.

Hm yeah I think Orteil also faces the problem of a codebase that is so massive and unruly that it just takes very long to implement any real updates.

I understand that the code from `Sim.js` is not really understandable. As you can see from the issue list I have not had time to look at it myself. The `.caller` function not working is being tracked by #558 and is only a problem on the dev-branch.

I appreciate that the code is not correct or perfect and for the last months I have been trying to improve it. I am not the original author of 90%+ of the code and have found a lot of inconsistencies and problems already. You might want to look at version 2.021.2 to see where it has come from. With such a large project and its current state you have to pick your battles. If there is a way to allow the project to use NPM without forcing people to use NPM I think we should add it. If this is not possible I think we should hold off for now and first focus on at least annotating all functions and checking if everything that is already in the code works as expected (which I know right now is not the case).

**Comment by hyoretsu** [comment]
> most experienced JS developers will use it.

Not experienced programmers actually, it's the second thing I was taught. First an IDE recommendation, [VSCode](https://code.visualstudio.com/), and then NPM packages that help a lot, like ESLint+Prettier.


> Talking from my own experience, I only knew Python before starting on this. If I would have had to download NPM and understand how that works I would be much less inclined to help out in the first place.

I started using NPM after 1 month of searching what JavaScript I needed to use on Google. Depending on what you used to do with Python, I too would install a linter, as did I on VSCode even though I don't code in it. (Python extension, Black formatter) Basic programmer tool. It's like our version of auto correct, a feature every mobile keyboard has.
It's not like this is PNPM, a package manager that not many people use and needs some tinkering to work. (the one I normally use)


> but in a project that is relying on successive contributors that do not really communicate with each other (as they have often left the project when new ones start to join) I think it is paramount to make contributing/joining as easy as possible.

Tbh I only know of Aktanusa working on it, then him abandoning it and other people creating forks of Cookie Monster. Then you came back last year, somehow getting write permission on the original repo.


> Hm yeah I think Orteil also faces the problem of a codebase that is so massive and unruly that it just takes very long to implement any real updates.

Which also comes from the same problems CM has, he only has one huge file with no linting or anything. He doesn't even use an IDE, he still uses freaking Notepad++ to write JavaScript to this day. And in his case he insists on supporting the 5% of browsers that still don't support ES6, so he can't even hide his bad code some more and has to use outdated stuff.


> I understand that the code from `Sim.js` is not really understandable. As you can see from the issue list I have not had time to look at it myself.

Not quite "not understandable", I can easily go to each function an read what it does. But from what I could skim, you can simply delete `Sim.js`. It doesn't even account for injections into vanilla functions from mods. Only a handful of things from there are actually used, other than there's no reason to not use their vanilla counterparts.


> The `.caller` function not working is being tracked by #558 and is only a problem on the dev-branch.

I don't see a point to using that, even more so when there's 4 `.caller`. I've never used it, but I'm 100% sure you wouldn't need to repeat it 4 times.


> If this is not possible I think we should hold off for now and first focus on at least annotating all functions and checking if everything that is already in the code works as expected (which I know right now is not the case).

First step towards making it more approachable is actually organizing it, refactoring the code into smaller files that can be easily checked and understood. (ES6 modules, with `import/export`) Not sure if it's already in the plans.
Aside from adding comments for documentation that is. I can check what the functions do, but I still struggle on simply opening a 4k lines file. I often have to restart my VSCode after opening big files like those.


> The thing is that we would like the project to be accessible to as many people as possible.

I'm just gonna say it though, only 7 people (aside from you) committed since 2020, and out of those:

- 2 work on other mods (so they're experienced, contributed pretty heavily, one of them also uses TS)
- 1 uses TypeScript, NodeJS, NPM and stuff (so also experienced, and his commit only had a really small change)
- 1 plans on doing Computer Science grad, so he's surely doing some research into stuff
- and 1 changed 3 characters.

Out of the 23 people in total who contributed in a whole 7 years. Half (11/23) only have a single commit, and 7 of those only have 3 or less *really* minor changes. Most of the time only a single character was changed.


> If there is a way to allow the project to use NPM without forcing people to use NPM I think we should add it.

But seeing how Cookie Monster's too problematic for even me, who uses TypeScript instead of JavaScript, my last commit simply made ESLint+NPM an extra. I would have to venture far too deep to implement the other basics. (unwelcoming to even "experienced" programmers, let alone newbies)
In the latest commit I only added:
- a proper ESLint installation with NPM(doesn't enforce/require anything anymore)
- Fixed the hundreds of errors that appeared after applying `airbnb-base` preset (Lots of `var`'s and == still left over)
- I had to remove `caller.caller.caller.caller` because I don't know what was causing that error.

You probably want to edit your `ESLint.yml` to run on all source files instead of merged one, as those are the ones in which the code being clean actually matters.

**Comment by DanielNoord** [comment]
Okay, I have thought about this some more and maybe I had a bit of tunnel-vision in the beginning. NPM does offer some real benefits and some of the disadvantages I thought of might actually not be that important. We can at least try to use NPM for some time and see if it gives us any problems. Hopefully it doesn't! Sorry for being too strict.

At the moment I have no time to fully familiarize myself with NPM and completely check this PR. In the meantime I have pushed two commits that removed my mail and updated the ESLint Action. When I have some more time for this project I will read up on NPM and solve this PR.

**Comment by hyoretsu** [comment]
On a side note for #561, since you added Aktanusa as `author` in package.json, the email listed should be his, as the `author`/`contributors` specifically are meant to refer to a git user/person. E.g. "someone" wants to contact that person, not neccessarily about the repo, maybe to offer a job for him. His email is chanam.geo@yahoo.com (This is all info that's public on git, just `git log`)
Btw you have different names for local git and GitHub if that bugs you, DanielNoord does all the pull requests and Daniel (no ë) van Noord does the commits. (GitHub still recognizes them as same account though, but to git they're technically 2 different authors)

**Comment by DanielNoord** [comment]
Good catch. Missed that when copying and pasting names around.

I have changed my name on Github. Hopefully my local git and Github now have the same name!

**Comment by DanielNoord** [comment]
I am closing this PR as I have now added everything we currently need from npm.
In the future we might want to start working with modules as well but that is not the topic of this PR and will need to wait on solving all current open issues.
Thanks for you suggestion, I think it will help keep the project manageable in the future!

**Comment by hyoretsu** [comment]
Do keep in mind that not using Prettier also won't format identation, so it may have different amounts of spaces or tabs across the 6k+ lines.

**Pull request closed without merging**
