### PR TITLE
replaceAll is not defined

### LINKED ISSUE #775: Krumblor causes a crash
**Describe the bug**
Hatching Krumblor, or loading the script with Krumblor as a hatchling, causes some incorrect behavior.

Hatching Krumblor locked up the page.

Loading the script with the hatchling fails to display the GC timer, the bottom bar shows math errors for the PP value and timers, highlighting on the buildings on the right-hand side are incorrect and the buttons to purchase upgrades don't work.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load script
2. Hatch Krumblor
3. Wonder why nothing is happening any more.

**Save file**
```
Mi4wMzF8fDE2MTk0ODk4OTQ5ODc7MTYxODk0ODA4Mzg5NjsxNjE5NDkxMzEzMzc4O0FsbCA0IERhIENvb2tpZTtpbm50dXwxMTExMTEwMTAwMDEwMTEwMDEwMTB8MTQyNjI3MDY5Ljc4MDYyMTY7NzYyMjM3MDQxLjc4MDU4NzE7MTIwMjk7OTA4OzQzMjMxOTc1Ljk1NDA4MTk7MTcwOTswOzA7OTkzMDg0OTk2MzA3MDcwNjAwMDA7MDswOzA7MDswOzE7MTswOzA7MDswOzA7MDs7MDswOzQ2MzsyMzs0NDA7MDswOzEwODstMTstMTstMTstMTs2OzA7MDswOzEwOzA7MDswOzY7MTYxOTQ0NDA1NzkyOTswOzE7OzQxOzA7MDsyOTAzMjM1Ljg0ODU3NjM1ODU7fDEwMCwyMDAsNjI1NTg3MzksMCwsMCwxMDA7NzAsNzAsNzQ4MDE4MzEsMCwsMCw3MDs0MCw0MCw0NTI3MjA3NCwyLDE2MTk0OTE0NzkwMzk6MDoxNjE5NDg5ODk1MDE1OjA6MDo1NjowOjA6MTYxOTQ4OTg5NTAxNTogMTEwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCw0MDszMCwzMCwxNDA1MTg4MDcsMCwsMCwzMDsyMCwyMCwyMTgyNzI1NDEsMCwsMCwyMDsxMCwxMCwxMDM1ODc1MTksMSwwOjA6MTowOjA6IDc1NDoyOi02OjUwODowOjA6MCExMjIxOjI6LTQ3Ojc5MTowOjA6MCExNzc4OjU6LTMxOjgzMzowOjA6MCE0MjM3OjE6MjI6ODUzOjA6MDowITUyMzA6MDoxMTo0MzA6MDowOjAhNjQzMToxOjE3OjY3NTowOjE6MCE1Nzk1OjI6LTY2OjI4MzowOjE6MCE4MDc2OjA6MTE6NjY3OjA6MTowITkxNDI6NDotODg6MjM2OjA6MTowITEwMjYxOjE6MTA6NDc5OjA6MTowITExMDk4OjE6MTI6NDQyOjA6MTowITEyMjUwOjM6NTk6NjMzOjA6MTowITEyMDg1OjI6LTU1OjU2MDowOjE6MCExMzEyODoyOi01Mjo2MjQ6MDoxOjAhMTQ4NzA6MDotMjo4NDc6MDoxOjAhMTYzMDg6MToxMDoyOTM6MDoxOjAhIDAsMCwxMDsxMCwxMCw3MzkyNjQ1NSwxLDEwLy0xLy0xIDIgMTYxOTQ5MTI3NDYwNyAwLDAsMTA7MCwwLDAsMSw1IDAgMjQwIDAsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDt8MTExMTExMTExMTEwMDAxMTExMTExMTExMTExMTExMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTEwMTExMDEwMTAxMDEwMTAxMDEwMDAwMDExMDAwMDAwMDAwMDAwMDAxMDEwMTAwMDAwMTExMTExMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTEwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMDAwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwfDExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTAxMTAxMTAxMTAwMDAxMTEwMTExMTExMTAwMDEwMTEwMTExMDEwMDExMDAwMDAxMTEwMDEwMDAwMDAwMDAxMTEwMDAwMDEwMDAwMDAwMDAxMDAwMDAwMDAwMDAxMTAwMTEwMDAwMDAwMDAxMTAwMDAwMDAwMTExMTAwMTExMDAxMTEwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJmYXZvdXJpdGVTZXR0aW5ncyI6W10sInNldHRpbmdzIjp7IkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjMsIkF2Z0NsaWNrc0hpc3QiOjAsIkNhbGNXcmluayI6MCwiU2NhbGUiOjIsIlNjYWxlRGVjaW1hbHMiOjIsIlNjYWxlU2VwYXJhdG9yIjowLCJTY2FsZUN1dG9mZiI6OTk5OTk5LCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIlBQRGlzcGxheVRpbWUiOjAsIkJ1aWxkQ29sb3VyIjoxLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlBQRXhjbHVkZVRvcCI6MCwiUFBSaWdpZGVsTW9kZSI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIkJvdEJhciI6MSwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjIsIlVwQmFyQ29sb3VyIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjEsIlNvcnRCdWlsZGluZ3MiOjAsIlNvcnRVcGdyYWRlcyI6MCwiRHJhZ29uQXVyYUluZm8iOjEsIkdyaW1vaXJlQmFyIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhpZGVTZWN0aW9uc0J1dHRvbnMiOjAsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2x0aXBBbW9yIjowLCJUb29sV2Fybkx1Y2t5IjoxLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjoxLCJUb29sV2FybkNvbmp1cmUiOjEsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MSwiVG9vbFdhcm5FZGlmaWNlIjoxLCJUb29sV2FyblVzZXIiOjAsIlRvb2xXYXJuQm9uIjoxLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjowLCJVcFN0YXRzIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIlRpdGxlIjoxLCJHZW5lcmFsU291bmQiOjEsIkdDTm90aWZpY2F0aW9uIjowLCJHQ0ZsYXNoIjoxLCJDb2xvdXJHQ0ZsYXNoIjoiI2ZmZmZmZiIsIkdDU291bmQiOjEsIkdDVm9sdW1lIjoxMDAsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MCwiRm9ydHVuZUZsYXNoIjoxLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjZmZmZmZmIiwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjoxMDAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjoxLCJDb2xvdXJTZWFGbGFzaCI6IiNmZmZmZmYiLCJTZWFTb3VuZCI6MSwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkNvbG91ckdhcmRGbGFzaCI6IiNmZmZmZmYiLCJHYXJkU291bmQiOjEsIkdhcmRWb2x1bWUiOjEwMCwiR2FyZFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTAzLzEwMzA0Nl84NjE3MTQtbHEubXAzIiwiTWFnaWNOb3RpZmljYXRpb24iOjAsIk1hZ2ljRmxhc2giOjEsIkNvbG91ck1hZ2ljRmxhc2giOiIjZmZmZmZmIiwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MSwiQ29sb3VyV3JpbmtsZXJGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlclNvdW5kIjoxLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjowLCJXcmlua2xlck1heEZsYXNoIjoxLCJDb2xvdXJXcmlua2xlck1heEZsYXNoIjoiI2ZmZmZmZiIsIldyaW5rbGVyTWF4U291bmQiOjEsIldyaW5rbGVyTWF4Vm9sdW1lIjoxMDAsIldyaW5rbGVyTWF4U291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNTIvMTUyNzQzXzE1NjYzLWxxLm1wMyIsIkJ1bGtCdXlCbG9jayI6MCwiRmF2b3VyaXRlU2V0dGluZ3MiOjEsIkhlYWRlciI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RhdGlvbiI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIkNoYWluIjoxLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIk1pc2MiOjEsIkluZm9UYWIiOjF9fSwidmVyc2lvbiI6IjIuMDMxLjcifTs%3D%21END%21```

### PR DESCRIPTION
**Pull request by harbinger0x7c0**
replaceAll isn't a valid string method. We can replace it with 2 calls to replace("'","") in sequence to achieve the same effect, since we're just stripping quotes off these names so we know that there are only ever 2 quotes to remove.

This will close #775.

### CODE REVIEW

**Comment by DanielNoord** [comment]
You will need to make the edit to the source file found in the `src` directory and then use `npm run build` to build the final CookieMonster.js file.

Does this fix the issue you described in #775? Because I can't seem to reproduce #775 and therefore don't know if does so.

**Comment by harbinger0x7c0** [comment]
Yes, it does fix #775. I'll see about making your changes tomorrow as it is quite late here.

**Comment by DanielNoord** [comment]
Good to hear! I might be able to fix this myself today, but sadly can't make any promises..

**Comment by harbinger0x7c0** [comment]
You know, I just did a bit of googling and this may be a backwards compatibility issue. I can see that replaceAll is a part of the language, and the browser I'm running this in *might* be crazy out-of-date. Somebody might want to have a think about whether this is a fix worth having. Maybe it would be better to just close #775 as wontfix.

**Comment by DanielNoord** [comment]
Which browsers are you running? Perhaps another function that is supported by your browser can also do the trick!

**Comment by harbinger0x7c0** [comment]
It's definitely a browser issue. I loaded up the save on the latest Chrome without issue.

The browser that has the problem is Chromium 78, so yeah it's been a while.

I'm gonna close this PR, as the correct resolution is to run some dang updates. :-p

**Pull request closed without merging**
