### PR TITLE
Add toggle to prevent upgrade bar from scrolling

### PR DESCRIPTION
**Pull request by InSimpleTermsJordan**
Untested, but hopefully I did everything right. Not sure how to keep the offset for the rest of the buy column though, so hopefully this can be improved.

### CODE REVIEW

**Comment by Aktanusa** [comment]
I took a quick look and indeed it seems incomplete.  The checking of the config is not there and the changes when you toggle off are missing also.  Also, can you change the target to dev branch instead?

**Comment by InSimpleTermsJordan** [comment]
Hey, not sure if you got the notification, but I edited the /src/ files and changed the target branch. Just for clarity, should I remove the edits to the main CookieMonster.js file?

**Comment by Aktanusa** [comment]
I saw, sorry for the delay.  I've not made the time to work on this recently.  Very sorry.  I do want to eventually get to it though.  Please be patient with me.

**Comment by InSimpleTermsJordan** [comment]
No problem. Just didn't know whether commits sent a notification or not.

**Comment by Aktanusa** [comment]
Ah, yes it does.  And to answer your question about CookeiMonster.js, as long as it's the same as what is generated by the Combine scripts, no, you don't need to remove the edits.

**Comment by DanielNoord** [comment]
I have implemented this config-option in #323.

**Pull request closed without merging**
