### PR TITLE
Lucky prestige stats

### PR DESCRIPTION
**Pull request by jshepler**
Calculates when to reset to enable "Lucky Digit", "Lucky Number", and "Lucky Payout" upgrades on the ascension screen and shows the numbers on the stats view.

### CODE REVIEW

**Comment by Aktanusa** [comment]
So I've finally had some time to take a look and this looks very interesting!  I really hope I can add this in the future.  Thanks for your contribution!

**Comment by jshepler** [comment]
Sure. Feel free to changing wording or rename variables. I'm pretty bad at wording/naming things. I looked at the commit to remind myself what this does and the stats' labels and variable names didn't make any sense considering what I think the intention is (showing number of remaining something before a reset should be done).

https://martinfowler.com/bliki/TwoHardThings.html

**Comment by Aktanusa** [comment]
Great link, lol.

**Comment by bitsandbytes1708** [comment]
I reviewed the code, and it looks good! I'll go ahead and merge it now.

**Pull request merged**
