### PR TITLE
2000ms delay on load steam

### PR DESCRIPTION
**Pull request by ghost**
Increased delay from 300 to 2000ms. This is my first pull request, hope everything is okay.

### CODE REVIEW

**Comment by DanielNoord** [comment]
Almost correct!
Do you have `npm` installed?

**Comment by ghost** [comment]
No I don't.

**Comment by DanielNoord** [comment]
Then it will be difficult to fix the check. I will do this when I get home, thanks for your help!

**Comment by DanielNoord** [comment]
I have added a commit that increases the delay to 2000. Could you test for me?

**Pull request closed without merging**
