### PR TITLE
Sort buildings and upgrades by PP

### PR DESCRIPTION
**Pull request by fabianf1**
This pull request adds the ability to sort buildings and upgrades based on PP.
The buildings part has been taken from #219, but with changes to solve the conflicts.

Also note issue #151, which is about the sorting of buildings.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Thanks, I feel really bad for taking so long =(

**Comment by WesleyM77** [comment]
I like this! Any idea when it might get merged?

**Comment by Aktanusa** [comment]
No idea really, just be patient with me, sorry =(

**Comment by bitsandbytes1708** [comment]
Will this be merged soon? It has been several months now :)

**Comment by bitsandbytes1708** [comment]
@DanielNoord I reviewed the code and it looks good, should I go ahead and merge it?

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
