### PR TITLE
add flash/sound on full magic (hack)

### PR DESCRIPTION
**Pull request by jacekkopecky**
I'm now at a stage where I often wait for magic to refill. It's nice to have a flash and a sound for that. I've hacked it together here, reusing the reindeer sound. It may want a new option or a few, I dunno, works for me. Thoughts?

### CODE REVIEW

**Comment by Aktanusa** [comment]
Interesting idea to add that as a sound effect.  Hmm... I'll take a look.

**Comment by DanielNoord** [comment]
This should be accompanied with a config-option for this sound.

**Review by DanielNoord — CHANGES_REQUESTED** [review]
Add a config-option for this sound, similar to all other sounds created by CM.

**Comment by jacekkopecky** [comment]
sorry, this is well old, I'm unlikely to come back to it

**Comment by DanielNoord** [comment]
Understandable, closing this PR and re-issuing the add-in.

**Pull request closed without merging**
