### PR TITLE
Missing Garden Seeds

### PR DESCRIPTION
**Pull request by BONNe**
Made changes that will show Missing Seeds in Garden panel under Unlocked seeds.

[Missing Seeds image](https://image.ibb.co/bHSC8U/Missing_Seeds.png)

### CODE REVIEW

**Comment by Aktanusa** [comment]
Once again, great work!  Sorry I've been slow.  I will merge, I promise!

**Review by DanielNoord — CHANGES_REQUESTED** [review]
This will need to be updated to resolve any conflicts with CM 2.031

**Comment by BONNe** [comment]
Well, it was a long ago when I created it...
I need to remember what I did :D

**Comment by DanielNoord** [comment]
@BONNe are you still interested in implementing this in the near future? Or should I schedule this feature for a later release?
I am aiming for a new release in about a week.

**Comment by BONNe** [comment]
I will try to finish it up by Wednesday.

**Comment by DanielNoord** [comment]
You might want to take a look at [Cookie Clicker Agronomicon](https://github.com/Acharvak/Cookie-Clicker-Agronomicon).
While it hasn't received updates in a while, its way of showing obtainable seeds is actually quite nice.
As [HortiCookie](https://klattmose.github.io/CookieClicker/Horticookie.js) by @klattmose also depends on it we might run into trouble if we implemented our own solution.
Perhaps it is better to implement a similar solution, or directly load Agronomicon upon loading of CookieMonster, or absorb Agronomicon into CookieMonster as @acharvak suggests in the ReadMe.

**Comment by BONNe** [comment]
So I checked Agronomicon, and it's implementation is much nicer. I will close this one.

**Pull request closed without merging**
