### PR TITLE
Add the 'next multiple of 50' information to buildings' tooltip

### PR DESCRIPTION
**Pull request by lgeorget**
This is a small additional feature that adds a (useful to me at least :p) piece of information to a building's tooltip: the number of buildings of its kind missing to reach the next multiple of 50 (susceptible to trigger an achievement) and the total price.

We could further develop the idea b adding the time left before being able to buy, or the name of the achievement reached at the next multiple of 50, etc.

### CODE REVIEW

**Comment by lgeorget** [comment]
Added the 'time left' information.

**Comment by Aktanusa** [comment]
Interesting idea, though can you do the pull request on the dev branch instead of master?  Master is for when it's been tested fine from dev.

**Comment by lgeorget** [comment]
Oh, sure! Switched!

**Comment by Aktanusa** [comment]
Thanks.  So I really plan to do this request and hopefully not take as long as the other pull request.  I'll have some time soon to finally do both requests.

**Comment by lgeorget** [comment]
Cool! I rebased my branch to the dev branch so that hopefully it will just be a fast-forward git merge for you.

**Comment by lgeorget** [comment]
I rebased my pull request onto your master branch.

**Comment by Aktanusa** [comment]
Sorry that I've been taking a long time to do this.  I am making more time to do development on CM, so you should see this being merge soon.

**Pull request merged**
