### PR TITLE
Fixed Golden Cookie percentage calculation to cdf #921

### LINKED ISSUE #921: Golden cookie percentage always shows as "<0%"
**Describe the bug**
With the newly added percentage next to the "next cookie" and "next reindeer" bars I expect the number to increase from 0 to 100% chance (that a cookie/reindeer will appear during the next tick) as the number of seconds left counts down to 0.

Currently the number to the right of the bar always reads "<0%" instead.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load my save file below
2. Look at the bar up top
3. Wait for the gray portion of the bar to disappear (the time during which there is a lockout on the appearance of the next cookie/reindeer)
4. the % continues to say <0 as time goes on

**Screenshots**
Since the gray bar for Next Cookie is gone the percentage should be increasing above 0%
image

**Save file**
Mi4wMzF8fDE2MjY0Njg3ODE1NTY7MTYxMDc0ODI4MzQ5NzsxNjI3NTg2MjEwODkxO0tldmluO3hwcGJ0fDExMTExMDAxMDAxMDAwMTAwMTAxMHw5LjU0MzU4MDI4NzkzNjI0NWUrNDY7MS4wMjgwNTEwMjY5NjMyODAyZSs0NzsxNjY3MzsyOTI2OzEuNDYxODY3MDM4NjAxNTgwMmUrNDY7NjM0NTs1OzI0OzIuMDc0NDQxNjcwMzk1NTMxNGUrNDc7Mzs1OzA7MDstMTs4OzIxMDs0LjgxMDI2ODIxMzYyMTQwM2UrNDQ7Mjk3OzE0OzQwOzI1NzgwMzI7NjtjaHJpc3RtYXM7MS4xMjcyNzMwNjkxNDgzMDkzZSs0NTsxMTs1OTE5NzA5Njk0Nzk7MjA4MDEwNDk3MTc7NTcxMTY5OTE5NzYyOzA7MDs0NjI7NDk0OzY2MTs0NDI7NjEzOzI1OzEwOzQ7MDszOzA7MDs3OzE4NDsxNjI3NTg2MTk3MjAzOzA7MzsyMjcsMTI5LDM0Mzs0MTsxOzE7My44NzUyMjQ1NDY2MzY2MmUrNDA7fDY1NiwxMDA2LDguOTU2NTI4MTEyNjEwMDg0ZSs0MywxMCwsMCw2NTY7NjQyLDk5MiwzLjI2MDIxOTcyNTI2NjIzMTdlKzQzLDEsLDEsNjQyOzYxMCw5NjAsMS41NzEyMjU3NjE4NzMxMjVlKzQwLDEwLDE2MjcwNjQ3NDM5MTc6NDoxNjI3MDYxMjgyMDg0OjE6Mzg6NzI1OjE6MDoxNjI2NDY4NzgxNTc1OiAxMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDYxMDs2MDAsOTUwLDEuMDYxNzY3NzA4NTI0NjEwOWUrNDIsMSwsMSw2MDA7NTc2LDkyNiwxLjczNTI1NTA4NTA3NTYyMzNlKzQxLDEsLDEsNTc2OzU1OCw5MDgsNC4wOTMwMzAzMjU1MTE5MzNlKzQwLDEsMDowOjE6MDowOiAxMDQwOjU6LTY0OjE2NjowOjA6MCE1MDc6NTotOTA6MzQ2OjA6MDowITU2MzA6MTo0NTo0Mjk6MDowOjAhMTc4Mjo1Oi00MjoyMDA6MDowOjAhNjcwODoxOjQwOjIwNDowOjA6MCE2Mjc3OjA6LTg6NzE4OjA6MDowITc5NDk6NTo1MDoyNDc6MDowOjAhODIyMTowOjEwOjk4OjA6MDowITEwMTIxOjE6MTM6NzE6MDowOjAhMTA2NTU6MToxMTozOTA6MDowOjAhODY5MjoyOi0zODo0MDE6MDowOjAhMTAyNzY6MjotNjc6MzY2OjA6MDowITExMTE4OjI6LTM5OjMwMjowOjA6MCEzNTUyOjQ6LTIwNzoyMDA6MDowOjAhMTIzMDA6MjotNDY6MTUwOjA6MDowITE2MDIyOjA6LTk6MjY2OjA6MDowISAwLDEsNTU4OzUzOSw4ODksMS42OTIwOTk0MjMwOTEyNDg1ZSs0MSwxLDEwLzkvNiAzIDE2MjY3ODA3NDE1OTMgMCwxLDUzOTs1MjAsODcwLDUuODQxNDIwOTAwMzA4MjE1ZSs0MCwyLDE2LjUyODI1OTUxNzU1MzM0NCAyNCA0MzggMSwwLDUyMDs1MDEsODUxLDIuMDY3MDA2NzQxMzA5ODU5NWUrNDAsMSwsMSw1MDE7NDgyLDgzMiw1LjUzMjU0NjY5ODg5NzM4NWUrNDAsMiwsMSw0ODI7NDYzLDgxNiw1LjE3MDQ0MjU5MDU5MTM5NzRlKzQyLDIsLDEsNDYzOzQ1MCw4MDAsMS4yNDQzNzExNDA4MjUxMTQ0ZSs0MiwyLCwxLDQ1MDs0MjgsNzc4LDguMTYzOTQ4MTU2ODA1NzllKzQyLDIsLDEsNDI4OzQxMCw3NjAsNC4yNTU1ODYzNTIwNDE0MzVlKzQzLDIsLDEsNDEwOzQwMCw3NTEsMS4xMDI5ODI5MTI1MTUzNThlKzQ0LDIsLDEsNDAwOzQwMCw3NTAsNS4wOTMzMjA4ODU0MjA4ZSs0NCwzLCwxLDQwMDszNTAsNzAxLDEuNDAwMTc3NzQ1NTIxNjY4NWUrNDQsMywsMSwzNTA7MzI2LDY3Niw0LjMzMzQ2MzU4Nzc4NTUzM2UrNDQsNywsMSwzMjY7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMDAxMTExMTEwMDEwMTExMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAxMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMTAxMDEwMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMDAwMDAwMTEwMDExMTExMTAwMDAwMDExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMTExMTExMTExMTEwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTExMDAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDExMDAxMTExMDAwMDAwMDAxMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTEwMTExMTExMDExMTExMTAwMDAwMDAwMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMDEwMDExMTEwMTExMDEwMDAxMDExMTExMTExMTExMTExMDExMTExMTExMTEwMTExMDEwMTEwMTExMTExMTExMDAxMTEwMTEwMDAwMDAwMTEwMDAwMDAxMDAwMDAwMDExMTExMTExMTExMTAwMDAwMDAwMDExMTExMTEwMDAwMDAwMDExMTExMTExMDAwMDAxMTEwMTExMTAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQ1BTTW9kZSI6MSwiQXZnQ1BTSGlzdCI6MSwiQXZnQ2xpY2tzSGlzdCI6NCwiQ2FsY1dyaW5rIjowLCJTY2FsZSI6MiwiU2NhbGVEZWNpbWFscyI6MSwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjoiOTk5OTk5IiwiVGltZUZvcm1hdCI6MCwiRGV0YWlsZWRUaW1lIjoxLCJQUERpc3BsYXlUaW1lIjoxLCJCdWlsZENvbG91ciI6MSwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjoxLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOiIxIiwiQ29sb3VyQmx1ZSI6IiM0YmI4ZjAiLCJDb2xvdXJHcmVlbiI6IiMwMGZmMDAiLCJDb2xvdXJZZWxsb3ciOiIjZmZmZjAwIiwiQ29sb3VyT3JhbmdlIjoiI2ZmN2YwMCIsIkNvbG91clJlZCI6IiNmZjAwMDAiLCJDb2xvdXJQdXJwbGUiOiIjZmYwMGZmIiwiQ29sb3VyR3JheSI6IiNiM2IzYjMiLCJDb2xvdXJQaW5rIjoiI2ZmMTQ5MyIsIkNvbG91ckJyb3duIjoiIzhiNDUxMyIsIkJvdEJhciI6MSwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjIsIkF1dG9zYXZlVGltZXJCYXIiOjEsIlVwQmFyQ29sb3VyIjoxLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjAsIlNvcnRCdWlsZGluZ3MiOjMsIlNvcnRVcGdyYWRlcyI6MSwiVXBncmFkZXNOZXZlckNvbGxhcHNlIjoxLCJEcmFnb25BdXJhSW5mbyI6MSwiR3JpbW9pcmVCYXIiOjEsIkdDVGltZXIiOjEsIkZhdmljb24iOjEsIldyaW5rbGVyQnV0dG9ucyI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MSwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjAsIlRvb2xXYXJuTHVja3lGcmVuenkiOjAsIlRvb2xXYXJuQ29uanVyZSI6MCwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjowLCJUb29sV2FybkVkaWZpY2UiOjAsIlRvb2xXYXJuVXNlciI6IiIsIlRvb2xXYXJuQm9uIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIlRvb2x0aXBQbG90cyI6MSwiVG9vbHRpcFBhbnRoZW9uIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjoxLCJVcFN0YXRzIjowLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoiNzc3Nzc3IiwiU2hvd01pc3NlZEdDIjowLCJUaXRsZSI6MiwiR2VuZXJhbFNvdW5kIjowLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MSwiQ29sb3VyR0NGbGFzaCI6IiNGRkVCNjciLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MjYsIkdDU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy82Ni82NjcxN185MzE2NTUtbHEubXAzIiwiRm9ydHVuZU5vdGlmaWNhdGlvbiI6MSwiRm9ydHVuZUZsYXNoIjoxLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjMkExN0ZGIiwiRm9ydHVuZVNvdW5kIjowLCJGb3J0dW5lVm9sdW1lIjo3OSwiRm9ydHVuZVNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTc0LzE3NDAyN18zMjQyNDk0LWxxLm1wMyIsIlNlYU5vdGlmaWNhdGlvbiI6MCwiU2VhRmxhc2giOjAsIkNvbG91clNlYUZsYXNoIjoiI0ZGQURGQyIsIlNlYVNvdW5kIjoxLCJTZWFWb2x1bWUiOjEwMCwiU2VhU291bmRVUkwiOiJodHRwczovL3d3dy5mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTIxLzEyMTA5OV8yMTkzMjY2LWxxLm1wMyIsIkdhcmRGbGFzaCI6MCwiQ29sb3VyR2FyZEZsYXNoIjoiIzdDRkY0QyIsIkdhcmRTb3VuZCI6MCwiR2FyZFZvbHVtZSI6ODgsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9wZW9wbGUvaG9kb21vc3R2YXJ1amVtcml0YW0vc291bmRzLzE3MTI3OS9kb3dubG9hZC8xNzEyNzlfX2hvZG9tb3N0dmFydWplbXJpdGFtX19sb3BhdGUxMi0zLndhdiIsIk1hZ2ljTm90aWZpY2F0aW9uIjoxLCJNYWdpY0ZsYXNoIjowLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MCwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MSwiV3JpbmtsZXJNYXhGbGFzaCI6MCwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNGRkZGRkYiLCJXcmlua2xlck1heFNvdW5kIjowLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJCdWxrQnV5QmxvY2siOjEsIkZhdm91cml0ZVNldHRpbmdzIjoyfSwiaGVhZGVycyI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RhdGlvbiI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIkNoYWluIjoxLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIkFjaGlldnMiOjEsIk1pc2MiOjEsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbIlBQT25seUNvbnNpZGVyQnV5YWJsZSIsIlBQRXhjbHVkZVRvcCIsIlBQU2Vjb25kc0xvd2VyTGltaXQiLCJHQ1NvdW5kIiwiU2VhU291bmQiLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IiwiTWlzc2luZ1VwZ3JhZGVzIiwiU29ydFVwZ3JhZGVzIiwiU29ydEJ1aWxkaW5ncyJdLCJ2ZXJzaW9uIjoiMi4wMzEuMTAiLCJsb2NrZWRNaW5pZ2FtZXMiOltdfTtjb29raWVNb25zdGVyRnJhbWV3b3JrOnsic2V0dGluZ3MiOnt9LCJoZWFkZXJzIjp7ImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXX07Y29va2llTW9uc3RlclNob3J0Y3V0czp7InNldHRpbmdzIjp7Imdsb2JhbFN3aXRjaCI6MSwib3BlbkluZm8iOnsia2V5IjoiSSIsImFsdEtleSI6ZmFsc2UsImN0cmxLZXkiOmZhbHNlLCJzaGlmdEtleSI6dHJ1ZSwiZGlzcGxheU5hbWUiOiJTaGlmdCArIEkifSwib3Blbk9wdGlvbnMiOnsia2V5IjoiTyIsImFsdEtleSI6ZmFsc2UsImN0cmxLZXkiOmZhbHNlLCJzaGlmdEtleSI6dHJ1ZSwiZGlzcGxheU5hbWUiOiJTaGlmdCArIE8ifSwib3BlblN0YXRzIjp7ImtleSI6IlMiLCJhbHRLZXkiOmZhbHNlLCJjdHJsS2V5IjpmYWxzZSwic2hpZnRLZXkiOnRydWUsImRpc3BsYXlOYW1lIjoiU2hpZnQgKyBTIn0sInN0YXJ0TGVnYWN5Ijp7ImtleSI6IkwiLCJhbHRLZXkiOmZhbHNlLCJjdHJsS2V5IjpmYWxzZSwic2hpZnRLZXkiOnRydWUsImRpc3BsYXlOYW1lIjoiU2hpZnQgKyBMIn19LCJoZWFkZXJzIjp7ImZhdm91cml0ZSI6MSwiZ2VuZXJhbCI6MSwib3Blbk1lbnUiOjEsImFjdGlvbnMiOjEsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEifTs%3D%21END%21

**Browser**
Chrome Version 91.0.4472.164 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Numbernaut**
Changes the Golden Cookie probability percentage to a cumulative percentage, yielding the cumulative distribution as described by @CptHampton [here](https://github.com/CookieMonsterTeam/CookieMonster/issues/921#issuecomment-1611947442)

resolves #921

### CODE REVIEW

**Comment by DanielNoord** [comment]
Please make the changes in the relevant files. The file you are changing should be the build output.

**Comment by Numbernaut** [comment]
Initially, I made the changes directly to the CookieMonster.js file, which I now realize wasn't the best approach. I also mistakenly pushed the entire repository, including generated files, which was not ideal.

I've since reset the branch, applied the changes only to the relevant src/ files, and have pushed the updated commit. The changes should now align with the expected workflow. Please review the updated pull request.

**Comment by DanielNoord** [comment]
Sorry just saw your message. Could you also run the build?

**Comment by DanielNoord** [comment]
Do you want this to be available on the normal version? Then we also need to run `build`.

**Comment by Numbernaut** [comment]
Did my last commit run the intended function?

**Comment by DanielNoord** [comment]
Yes it did.

I had a look at the code: shouldn't this be a toggle able feature? It seems like a breaking change that might not be appreciated by all users. Should we make this a setting to switch between the two calculations?

**Comment by Numbernaut** [comment]
I understand what u mean, but it would effectively switch between showing "<0%" nearly all the time and the proposed implementation (Probability that GC has spawned until now).

In the end, I am indifferent to both solutions.
Maybe someone else can implement the switch, or if I should do it some pointers to relevant code snippets would be appreciated as i never really did UI

**Review by DanielNoord — APPROVED** [review]
You know what, let's just merge this!

Thanks!

**Pull request merged**
