### PR TITLE
2.021-hotfix

### PR DESCRIPTION
**Pull request by darkenvy**
quick fixes to stop crashes and work with the latest version.

Did not do anything to add support for new code. Only stopped the crashes to get it working again asap.

### CODE REVIEW

**Comment by storgall** [comment]
Can I use this "version" somehow?

**Comment by storgall** [comment]
ok I found a way, if anyone would like to use it:

javascript:(function() {
    Game.LoadMod('https://cdn.statically.io/gh/darkenvy/CookieMonster/2.021-hotfix/CookieMonster.js');
}());

**Comment by Stanzilla** [comment]
`Game.LoadMod('https://cdn.statically.io/gh/darkenvy/CookieMonster/2.021-hotfix/CookieMonster.js');`

**Comment by Aktanusa** [comment]
Cool, thanks, I'll use your code as tips.  I may not exactly use your code, but I will give you credit.

**Comment by darkenvy** [comment]
> https://cdn.statically.io/gh/darkenvy/CookieMonster/2.021-hotfix/CookieMonster.js

oh my god. thank you for this amazing resource storgall!

> Cool, thanks, I'll use your code as tips. I may not exactly use your code, but I will give you credit.

Totally fine :). I woke up today, saw it was broke and knew I could fix it. I really appreciated your extension anyways so it was the least I could do ¯\_(ツ)_/¯

**Comment by Azmaeus** [comment]
Not sure how this was affected by the fix, but I'm seeing all Bonus Income and Payback Period results in the negative, which is throwing off the color-coding of the purchase prices. Otherwise this seems to work great!

**Comment by Stanzilla** [comment]
@Aktanusa do you need help maintaining this? You seem very overwhelmed, no offense.

**Comment by Aktanusa** [comment]
@Stanzilla If you mean overwhelmed by the new changes, then nah, this update just came in an inopportune time.  I still play the game and I use my own addon.  So I do need to fix my own addon to continue to use it on the new version.  Now if you mean overwhelmed in terms of adding new features, yeah, I've been putting them off as my interest in the game as not as high as it used to be, and I do feel bad for all the work other people have added as pull request, but I would still like to get to them eventually.

**Comment by Stanzilla** [comment]
@Aktanusa I meant mostly with merging PRs, some of them are super long standing.

**Comment by Aktanusa** [comment]
@Stanzilla yeah, I feel bad, but I want to make sure I understand what's going on, and I like to reformat the code to my code format also.

**Comment by Aktanusa** [comment]
Okay, I took a look at what you did.  I am sorry to say I don't see any useful changes.  Thanks for trying to help out though!  I'll still give you credit in trying to help out =)

**Pull request closed without merging**
