### PR TITLE
Add Average Cookies Per Second, Minute, Hour, Day

### PR DESCRIPTION
**Pull request by viktor-ku**
Hey, folks!

There is a small PR including average cookies calculation per second, minute, hour and day basis.

By the way it's the most fun PR in my entire life so far :smile_cat:

### CODE REVIEW

**Comment by Aktanusa** [comment]
Hi @viktor-ku.  Thanks for the pull request.  Here is 2 problems I see via quickly looking at your changes:

1.  Can you change your pull request to dev branch?  Everything goes through dev before master.
2.  I currently only save the history of the past hour.  You can't get the average CPS for day right now.

Glad you had fun!

**Comment by viktor-ku** [comment]
@Aktanusa yeah sure!

My idea is not to get average CPS from the past day but to predict how many cookies you are baking per second, minute, hour and day. So I think I implemented it because really history is not the point here.

**Comment by viktor-ku** [comment]
@Aktanusa hello?

**Comment by Aktanusa** [comment]
I'm still thinking about it.  Sorry for being slow.  I don't see the usefulness of it right now.  Also the data would be better off using what history is available.

**Comment by Aktanusa** [comment]
You didn't need to close it. D:  I just didn't get how you are using the current average CPS which is based on history and setting of how much history to predict the amount you get in the future.  Honestly a better estimate would be taking all the history (max 1 hour) and then using that to predict the future cookie gain.

**Pull request closed without merging**
