### PR TITLE
XX:XX:XX:XX:XX

### PR DESCRIPTION
**Pull request by JCBourgo**
I think I put everything to implement the time format. The pull request for patches is a bit weird, it was just a mistake on my side with branches. Other than that, it should be functional.
Solves issue #85

### CODE REVIEW

**Comment by Aktanusa** [comment]
Okay thanks.  I'll take a look at it later today.

**Comment by Aktanusa** [comment]
I do see one or two mistakes, but overall good job!  Now I did notice the new CM.Disp.FormatTime ignores the parameter format when it's in XX:XX:XX:XX:XX format.  Meaning there is no long format (when format = 1).  My original thought was to keep the long format, but I guess you prefer even the long format to be XX:XX:XX:XX:XX?

**Comment by JCBourgo** [comment]
I'd say that the XX:/XXd config should override the "format", since the goal of XX: is to keep a uniform length all the time. There's no point of having the XX: if its length varies.

**Comment by Aktanusa** [comment]
I can see that, though to me it looks bad for next HC time to keep saying 00:00:00:00:01 all the time, lol

**Comment by JCBourgo** [comment]
It does that? It's supposed to have Xs everywhere when times are too big. Oops.

**Comment by Aktanusa** [comment]
You misunderstood.  I mean when your CPS is high enough to gain a HC every second, the display would be constantly 00:00:00:00:01

**Comment by JCBourgo** [comment]
Oh. Indeed. I'll have to think of something for that.

**Comment by JCBourgo** [comment]
Could you explain what XXd does to counter this? Maybe I'll be able to apply something similar to XX:. Or maybe we'll have to show some "normal text" to work around it.

**Comment by Aktanusa** [comment]
Well XXd basically counters by not showing any thing if it's zero, but this is eactly why you wanted the XX:XX:XX:XX:XX format in the first place.  The text length doesn't keep changing, lol.  Right now not many are using long format, but HC was one of them.  It says 1 second for me most of the time.

**Comment by JCBourgo** [comment]
Well if it's CONSTANTLY shows nothing, nothing will be wobbling. So I think it would be right to accommodate for the format. I'll add it so it shows nothing if format==1 and time<1.

**Comment by Aktanusa** [comment]
I just went through the code, in CM only next HC stat uses format 1, lol.  But format 1 is used in all calls of Game.sayTime in CC.  That's a lot in stats like Legacy started or Seasonal event

**Comment by JCBourgo** [comment]
Just added it. Does it seem alright?

**Comment by Aktanusa** [comment]
CC uses Game.sayTime in 12 locations.  There is an option in CM to turn off the use of CM.Disp.FormatTime for CC though.

**Comment by JCBourgo** [comment]
With the condition I just added, I think it should be fine for what concerns us. What do you think? (yes it's only a change of one line, but it should work)

**Comment by Aktanusa** [comment]
Sorry, I think you completely misunderstood the problem.   Time less than 1 s was never a problem due to the line

`time = Math.ceil(time);`

My original concern was that it looked weird (to me, maybe not for you) to have the time to next HC stat show 00:00:00:00:01 all the time.  Maybe this is the confusion.  But now that I looked thur the code again, there are other spots using format = 1; namely in CC itself assuming you have the format option ON.  Hope I was clear.

**Comment by Aktanusa** [comment]
I've reread the thread, and I think I see the confusion is. I responded to your question with this:

> Well XXd basically counters by not showing any thing if it's zero, but this is eactly why you wanted the XX:XX:XX:XX:XX format in the first place.

I think you read that as XXd shows nothing.  I didn't mean it shows nothing, I mean it shows nothing for days, hours, mins, but not sec since there is >1 sec left.  Basically it shows "1 second".  To me (maybe not you) this looks nicer than 00:00:00:00:01

**Comment by JCBourgo** [comment]
Oh now I get it! It was indeed a bit confusing for me, lol. So, the real problem is that it would look weird to have the timer stuck at ...:01. So, the thing I have to do is to have something that looks nicer for things that have format = 1 when their time drops at 1 sec?

**Comment by Aktanusa** [comment]
Well it's really all a matter of opinion.  If it doesn't look weird to you, then there is no need to change it =p.

**Comment by JCBourgo** [comment]
But now that we agree on the same thing, I'm willing to change it! Give me a couple of minutes, I'll have it show only ":01" instead of the full length when format = 1. :P

**Comment by JCBourgo** [comment]
That should indeed look better. If there isn't anything left to change, I'm done for this part! :)

**Comment by Aktanusa** [comment]
I like that you are very active on this so I kind of feel bad when I mention things >_>.  Problem with ":01" is that people may question, does that mean 1 min left? 1 hour left?  If it was 00:00:00:00:01, there be no question it means 1 second.  Another problem is that it's great that shows for 1 second, but wouldn't you want it to be that short for anything less than 10 seconds?  Like ":09", ":08", ":07", etc...

Now before you go change anything (it will make me feel bad you doing all this work to maybe not be used), let's continue discussion.  Right now I am leaning towards your original code where you ignore format = 1, lol.

**Comment by JCBourgo** [comment]
I really like having someone else to comment, because it brings a different point of view. And I don't really care about the time it takes, since it's literally only like a minute to change that particular line. So, back to the original code and we remove the line that takes care of format? I mean, it would work, and that's pretty much the whole point. And again, don't feel bad to mention things, when I'll get a job I'll have to deal with this anyway, so better prepare sooner or later! :)

**Comment by Aktanusa** [comment]
Yea probably best to try it without that extra line and see how you like it.

**Comment by Aktanusa** [comment]
Yea probably best to try it without that extra line and see how you like it.

**Comment by JCBourgo** [comment]
Here, did it :)

**Pull request merged**
