### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanielNoord**
Removed some of the stuff about the beta (as that link does not work anymore) and cleaned up here and there.
@Aktanusa is this okay with you?

### CODE REVIEW

**Comment by DanielNoord** [comment]
With #456 we now do take into consideration some of the clicking-upgrades, so I have changed the Readme to reflect that.

**Comment by Aktanusa** [comment]
Wait, the beta link doesn't work?  Or do you mean that beta needs to be updated first?

**Comment by DanielNoord** [comment]
No, same goes for the dev-branch link. rawgit.com is being phased out and it seems the github pages for the beta-branch also does not work anymore. The current link returns a file with version 2.016.1 while the CookieMonster.js file on the beta-branch is on 2.031.1 (I did not update it to 2.031.2 as I knew it was broken anyway).

**Comment by Aktanusa** [comment]
hmm, is there an alternative?

**Comment by DanielNoord** [comment]
I am not sure (not that experienced with GitHub pages) and I can not test since only the owner of a repo can do that I believe.
But I think it should be possible to publish multiple branches to GitHub pages.

**Comment by Aktanusa** [comment]
Hmm, I'll try to take a look then when I get a chance.  Sorry, no ETA though =(.

**Comment by DanielNoord** [comment]
Are you okay with removing them from the Readme in the meantime?
This will solve some confusion with new visitors to the page.
If so, I will open an issue so we won't forget to look at this.

**Comment by Aktanusa** [comment]
Sure!

**Pull request merged**
