### PR TITLE
fix: duplicated cookie notation

### LINKED ISSUE #1016: [Steam] Double notation
### Bug description

Using any of the Cookie Monster shortened notations results in doubled abbreviations. 

image

### To reproduce

1. Change to any shortened notation option other than "game's notation"

### Screenshot

_No response_

### Save file

Mi4wNDJ8fDE2MzM0NjA2ODE1MzA7MTYzMzQ2MDY4MTUzMDsxNjMzNjMwNDkxNjI5O1F1aW5uZWxsO2Jwc3BvfDExMTExMTAxMTExMDExMTAwMTExMDExMDAwfDMxNTc3NDgxMjU3NDEuOTQ5Ozg0MzY3MTAxNjY5MDgxLjQ0Ozk0MTYyOzMwNDsyNTkyMzkxMDg2NTU2MS40MjY7MzM1OzA7MDswOzA7MDswOzA7MDswOzMwNDswOzA7MDswOzA7MDs7MDswOzA7MDswOzA7MDstMTstMTstMTstMTstMTswOzA7MDswOzc1OzA7MDswOzE7MTYzMzU1NDg4MzczNDswOzA7OzEwMDswOzA7MTQ1MTExOTY0OS41Mzk1NDc7MDt8MTQ2LDE0NiwxMzc1ODM4MTk2MTcsMCwsMCwxNDY7MTUwLDE1MSwyMTQyMTY5MzU1ODUsMSwsMSwxNTA7MTIwLDEyMCwxOTk2OTEyNzQwOCwwLCwxLDEyMDsxMDAsMTAwLDUwOTk1MjMwMzMzLDAsLDEsMTAwOzEwMCwxMDAsMTU5MzEwMDczNTQyLDAsLDEsMTAwOzcwLDcwLDUyODI5MzY5MTM5NywwLCwxLDcwOzYwLDYwLDE1NzI4MDc5NzQ2NTYsMCwsMSw2MDs1MCw1MCw0MzA1Nzg2OTE2ODQzLDAsLDAsNTA7MzcsMzcsMTAwMDU1MjMwNjMxMzMsMCwsMSwzNzsyMiwyMiwxMzE5NDEyMTY4NDE4NywwLCwxLDIyOzEwLDEwLDc0ODc2MzQ0MTMwMjksMCwsMSwxMDsxLDEsMTM2MTY2NjEwNTU2MSwwLCwxLDE7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMDAwMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTAwMDAwMDAwMTExMTEwMTExMTExMTExMTExMTEwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAxMTExMDAwMDAwMDAxMDAwMTAxMDEwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTAxMDAwMDAxMTExMTExMTAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDAwMTExMTExMTEwMDAwMTExMTExMTAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMXwxMTExMTExMTAwMDAwMDAwMTExMTExMTExMDAwMDAxMTExMTExMTAxMTExMTExMTExMTExMTAwMTAwMTAwMTAwMDAwMTExMDExMTExMTEwMDAxMDAwMDAwMDAwMDAxMDAwMDAwMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDExMTAwMDExMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQ1BTTW9kZSI6MSwiQXZnQ1BTSGlzdCI6MywiQXZnQ2xpY2tzSGlzdCI6MCwiQ2FsY1dyaW5rIjowLCJTY2FsZSI6MiwiU2NhbGVEZWNpbWFscyI6MiwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiUFBEaXNwbGF5VGltZSI6MCwiQnVpbGRDb2xvdXIiOjEsIlBQT25seUNvbnNpZGVyQnV5YWJsZSI6MCwiUFBFeGNsdWRlVG9wIjowLCJQUFJpZ2lkZWxNb2RlIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJDb2xvdXJCbHVlIjoiIzRiYjhmMCIsIkNvbG91ckdyZWVuIjoiIzAwZmYwMCIsIkNvbG91clllbGxvdyI6IiNmZmZmMDAiLCJDb2xvdXJPcmFuZ2UiOiIjZmY3ZjAwIiwiQ29sb3VyUmVkIjoiI2ZmMDAwMCIsIkNvbG91clB1cnBsZSI6IiNmZjAwZmYiLCJDb2xvdXJHcmF5IjoiI2IzYjNiMyIsIkNvbG91clBpbmsiOiIjZmYxNDkzIiwiQ29sb3VyQnJvd24iOiIjOGI0NTEzIiwiQm90QmFyIjowLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MiwiQXV0b3NhdmVUaW1lckJhciI6MCwiVXBCYXJDb2xvdXIiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjowLCJVcGdyYWRlc05ldmVyQ29sbGFwc2UiOjAsIkRyYWdvbkF1cmFJbmZvIjoxLCJHcmltb2lyZUJhciI6MSwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjoxLCJIaWRlU2VjdGlvbnNCdXR0b25zIjowLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MSwiVG9vbFdhcm5MdWNreUZyZW56eSI6MSwiVG9vbFdhcm5Db25qdXJlIjoxLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjEsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FybkJvbiI6MSwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJUb29sdGlwUGxvdHMiOjEsIlRvb2x0aXBQYW50aGVvbiI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiU3RhdHMiOjEsIk1pc3NpbmdVcGdyYWRlcyI6MCwiTWlzc2luZ0FjaGlldmVtZW50cyI6MCwiVXBTdGF0cyI6MSwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MCwiQ29sb3VyR0NGbGFzaCI6IiNmZmZmZmYiLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MTAwLCJHQ1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvNjYvNjY3MTdfOTMxNjU1LWxxLm1wMyIsIkZvcnR1bmVOb3RpZmljYXRpb24iOjEsIkZvcnR1bmVGbGFzaCI6MCwiQ29sb3VyRm9ydHVuZUZsYXNoIjoiI2ZmZmZmZiIsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjoxLCJTZWFGbGFzaCI6MCwiQ29sb3VyU2VhRmxhc2giOiIjZmZmZmZmIiwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjowLCJDb2xvdXJHYXJkRmxhc2giOiIjZmZmZmZmIiwiR2FyZFNvdW5kIjoxLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjoxLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjAsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MCwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJCdWxrQnV5QmxvY2siOjEsIkZhdm91cml0ZVNldHRpbmdzIjoxfSwiaGVhZGVycyI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RhdGlvbiI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGlmaWNhdGlvbiI6MSwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MSwiTm90aWZpY2F0aW9uR0MiOjEsIk5vdGlmaWNhdGlvbkZDIjoxLCJOb3RpZmljYXRpb25TZWEiOjEsIk5vdGlmaWNhdGlvbkdhcmQiOjEsIk5vdGlmaWNhdGlvbk1hZ2kiOjEsIk5vdGlmaWNhdGlvbldyaW5rIjoxLCJOb3RpZmljYXRpb25Xcmlua01heCI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjAsIkNoYWluIjowLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjEsIldyaW5rIjoxLCJTZWEiOjEsIkFjaGlldnMiOjEsIk1pc2MiOjEsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MX0sImZhdm91cml0ZVNldHRpbmdzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEwIiwibG9ja2VkTWluaWdhbWVzIjpbXX07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119O01FVEE6Y29va2llIG1vbnN0ZXIsKmNvb2xlciBzYW1wbGUgbW9kLCpsYW5nIHNhbXBsZSBtb2QsKnNhbXBsZSBtb2Q7%21END%21

### Browser / Steam / Version

Steam, version 2.042

### PR DESCRIPTION
**Pull request by dsf3449**
## Changes
- Removes HTML manipulation done in `DrawHook.js` regarding the amount of cookies.

## Explanation
Prior to 2.04(ish), the cookie multiplier (i.e. quadrillion) was included before the linebreak:
<details>
  <summary>Expand</summary>
  
  image
</details>

Now, it is in the string after the linebreak:
<details>
  <summary>Expand</summary>
  
  image
</details>

The notation was duplicated because we were replacing the string before the linebreak (which continued working), but the string after the linebreak now includes the notation.

Removing this code resolves the issue, since `ReplaceNative()` appears to replace the game's `Beautify` function (which the div now uses to generate it's value).
<details>
  <summary>Short Scale</summary>
  
  image
</details>
<details>
  <summary>Short Scale (Abbreviated)</summary>
  
  image
</details>
<details>
  <summary>Scientific Notation</summary>
  
  image
</details>
<details>
  <summary>Engineering Notation</summary>
  
  image
</details>
<details>
  <summary>Game's Scale</summary>
  
  image
</details>
<details>
  <summary>Metric</summary>
  
  image
</details>

## Issue
Fixes #1016

### CODE REVIEW

**Comment by DanielNoord** [comment]
@dsf3449 Thanks! Looks good to me.

Looking at the comment we're glad this can be removed 😄

**Comment by DanielNoord** [comment]
@dsf3449 I should have checked this before, but does this work on browser edition as well? Or is this only for Steam?

**Comment by dsf3449** [comment]
@DanielNoord It works on both steam and the browser version 👍

**Comment by DanielNoord** [comment]
Nice, thanks!

**Pull request merged**
