### PR TITLE
Adding support for content mods

### PR DESCRIPTION
**Pull request by DanielNoord**
As mentioned in #332 CM currently breaks upon finding an unknown object/upgrade/achievement.
By adding
 ```
if (you == undefined) {
	CM.Sim.InitData();
}
```
CM will now re-initialize the "database" of objects, upgrades and achievements.
This will still produce an initial error in the console, but will then be resolved.

Furthermore, as noticed by @staticvariablejames we currently called `CM.Sim.CopyData` with every loop.
This call has been moved outside of the loop.

### CODE REVIEW

**Comment by Aktanusa** [comment]
I'll repeat what I said in Issue #332.  'CM.Sim.CopyData' is inside the loop for a good reason.  Unless you undo the changes afterward, the calculation for each building afterward is incorrect.  Unless I missed something.  Please take a look closely.

**Comment by DanielNoord** [comment]
You are indeed correct. I'm sorry I was too quick to judge.
With #338 I have resolved the problem.

**Comment by Aktanusa** [comment]
That's okay.  Everyone makes mistakes.  If you have a question as to why I did something, don't hesitate to ask!  I only by chance noticed this one.  I sure didn't go through everything.

**Comment by DanielNoord** [comment]
Besides this edit we have not really changed anything in the way the calculations work, so all should be fine :)

**Comment by Aktanusa** [comment]
I was going to add that another reason why I also take a long time is because everything is kind of delicate.  Almost everything is in a certain order for a reason.

**Pull request merged**
