### PR TITLE
Fortune cookie effects

### PR DESCRIPTION
**Pull request by Azmaeus**
When a Fortune Cookie ("Fortune" in the News Ticker) is present, `(Game.TickerEffect && Game.TickerEffect.type == 'fortune')` will be True.

I added all configuration and function needed to both flash the screen and chime (I selected a chime that seemed to fit according to myself and my wife) similar to the GC and Reindeer. I tested that it works, the flash and chime happen when a Fortune appears in the ticker.

This does NOT include darkenvy's 2.021 fix, I figured you'll be getting that in separately, but let me know if you need me to pull that fix into this PR to merge it.

I also haven't taken any time looking into the feasibility of adding a countdown timer similar to GC - in my experience so-far a Fortune Cookie could appear within seconds of another, or could be minutes, so I don't suspect it would be very useful.

### CODE REVIEW

**Comment by Aktanusa** [comment]
Great work!  Can you set it to dev branch?  Everything goes there first.

**Comment by Azmaeus** [comment]
Changed to dev branch

**Comment by Azmaeus** [comment]
I had a minute to figure out the title, so I'm adding that. I was thinking I could put [F] at the very beginning because I don't think we need to have a timer indicating how much time is left before it goes away, and it makes it more likely to be seen on smaller resolutions or windows with more tabs open. Thoughts?

**Comment by Azmaeus** [comment]
I updated my branch with the above-mentioned change - when a Fortune Cookie is present, the title will have [F] at the front, otherwise it will not but will have the rest of the title as it behaved before this fix.

I have tested this, when I loaded I had my normal GC and Reindeer timers counting down followed by the bank count. As soon as a FC appeared the title changed to have [F] before the timers, then as soon as I clicked the fortune the title no longer had an [F] preceding but continued to display the other timers and bank.

**Comment by Aktanusa** [comment]
Nice touch.  I took a quick look and I may reorder what you did.  Thanks for keep my code format though, lol.

**Comment by Azmaeus** [comment]
Happy to help! If you need me to do anything let me know.

**Comment by Aktanusa** [comment]
I'll add this a bit later, since I'm sure people are waiting for just it working.  I don't think it be too long.  Maybe a day or two when I have some time again.

**Comment by Aktanusa** [comment]
@Azmaeus I've merge this pull, and I'm very impressed you followed my coding format almost perfectly.  Thanks a ton for this.

**Comment by Aktanusa** [comment]
So there is a minor bug with the code.  If by some lucky chance you get two fortune ticker back to back, the 2nd time you get the fortune ticker, CM won't notify you.  Since this is very unlikely anyway, I think it's okay to leave this bug unfixed as I can't figure a fix for it right now, lol.

**Comment by Azmaeus** [comment]
@Aktanusa hope it's okay to post on a closed PR. A fortune ticker can only appear if the ticker was not clicked, so that even lessens the chance of this happening. So yeah, there's a very small chance the ticker will present a fortune, and if the fortune is not clicked it could produce another fortune consecutively, and any consecutive fortunes will not chime. The best way I can think of to fix this would be to track also the text of the fortune, so if it changes and the last state is still 1 then it will chime again. I personally don't feel it's worth the effort  : /

**Comment by Azmaeus** [comment]
oh, and I love the sound (why I picked it)! I get it if you change it though, it is slightly more "large" than the other chimes you have used for other notifications.

**Comment by Aktanusa** [comment]
That's fine posting here.  Sorry, I had to change it since it is long, like you said.  Good thing you can change it back on your personal game =).  As for your suggested solution, there is an even smaller chance that you get the same text, lol.  But that chance still exist, so while it kind of works, it's not complete.

**Pull request merged**
