### PR TITLE
Feature/pp

### LINKED ISSUE #148: Add toggle to calculate PP based on what user can afford at the exact moment
Sometimes if I'm going to idle for a long time I spend my whole bank. This leads to the scenario where the most cost-effective thing is a chancemaker and I can't afford it, so I scan the numbers at the bottom and mouse over the upgrades to see what I should buy that I CAN afford.

### LINKED ISSUE #149: Option to give different colour to PP of buildings that cost less than "x seconds of CPS"
I might be alone/weird in doing this, but rational or not, one of the things I do sometimes is buy everything that is relatively cheap. Usually I aim for things with a cost of 1 or 2 seconds of production, sometimes up to 10.

Example: My production is 780 Quintillion CPS and farms cost only 52 Quintillion each. I'm going to buy farms until their cost is ~1 sextillion.

Suggestion: It would be nice to have a color applied to upgrades and buildings that are "cheap-as-free" as defined by a user-entered number of seconds of production default this null - feature is off.

### LINKED ISSUE #155: Option to exclude certain buildings when calculating PP
Because max mana effects the total time it takes to refill the mana bar I'm currently sitting at just 7 Wizard towers to maximize my baked goods casts.  This means that the building showing green is always wizard towers.  An optional flag to exclude them would restore functionality when pursuing this strategy.

### PR DESCRIPTION
**Pull request by DanielNoord**
This closes #149, closes #155, closes #148

### CODE REVIEW

**Comment by TakGalaman** [comment]
ooo I'm excited to try this out. I feel a bit foolish that I can't figure this out myself, but how do I run cookie monster from the dev or beta branches?

**Comment by DanielNoord** [comment]
Click the "code" tab at the top of this screen > click on the `CookieMonster.js` file > press `raw` > copy everything you see and paste it into your browsers console!

**Comment by TakGalaman** [comment]
*Cackling* this is amazing!!!

**Comment by DanielNoord** [comment]
Let me know if you run into any bugs!

**Pull request merged**
