### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by bitsandbytes1708**
Since we merged #319, (update for the latest version of Cookie Clicker) should we go ahead and merge the Dev branch into Master?

### CODE REVIEW

**Comment by DanielNoord** [comment]
Let's first clear up some of the older PR's that we can immediately add.
There might be some useful functions and updates to CookieMonster that we can add alongside the update to 2.031.

**Comment by bitsandbytes1708** [comment]
Ok

**Comment by bitsandbytes1708** [comment]
I think we've merged everything that is simple, everything else needs extensive review/resolving. Should we merge it now?

**Comment by DanielNoord** [comment]
No because I have already spotted some errors from testing the dev-branch.
I will update when I have fixed all errors.

**Comment by bitsandbytes1708** [comment]
@DanielNoord Ah,ok!

**Comment by bitsandbytes1708** [comment]
Did #329 fix all the errors you were seeing while testing it?

**Comment by bitsandbytes1708** [comment]
Great!

**Pull request merged**
