### PR TITLE
"Conjure Baked Goods" Tooltips & Stats

### PR DESCRIPTION
**Pull request by Onmar**
This Adds Warning/Caution Tooltips and Stat-Display for the "Conjure Baked Goods"-Spell.
It works in the same way the "Lucky!" Golden Cookie Tooltips work,
the code almost entirely copied over.

In Display.js some minor adjustments have been made to the Tooltip Variable Names, so it is clear which one is meant.

I have tested the edited file and it seems to be working fine.

This would include issue #130

### CODE REVIEW

**Comment by Aktanusa** [comment]
Whoa, this was unexpected.  Could you put it to dev branch first?  It's where I test before I move to master.

**Comment by Aktanusa** [comment]
Sorry for the delay, I'll get to this in a bit ~_~

**Comment by Aktanusa** [comment]
Okay, so I've started to look at this.  Here is a problem which I thought is a big problem, but I think now it is a simple problem.  Currently what you implemented is the amount needed when Golden switch is off.  There is a different amount when Golden switch is on.  The solution is to use the current Game.cookiesPs instead of the calculated one with Golden switch off.  Previously I did this because the only way to get a Lucky!/Lucky! (Frenzy) is when the Golden switch off.  With the advent of spells where you can get a Lucky! GC even with the Golden switch on, I think I need to revert back to using Game.cookiesPs.

**Comment by Aktanusa** [comment]
Okay, next problem.  With, again, the advent of mini games, you can have a Lucky! or Conjure Baked Goods anytime in combination with all sorts of CPS increasing buffs besides Frenzy.  Obvious other ones is Elder Frenzy and Dragon Harvest.  I will need to revamp quite a bit to allow custom CPS buff increase for the user as there can also be stacking buffs.  What I'm going to do is now allow the user to set whatever buff they want.  This is an idea that someone else proposed in the past already.  So this change might take a while.

**Comment by Ludenife** [comment]
Hi, is it possible to add to the spell tooltip the minimum requiered amount of cookies in bank for the current CPS ? For example if you get a lucky + fervent adoration, you can check how many cookies you would need to get the max amount. I think that would be a simple solution while you work on a more complex and complete one.

**Comment by DanielNoord** [comment]
This has been added with #334

**Pull request closed without merging**
