### PR TITLE
Missing Upgrades

### PR DESCRIPTION
**Pull request by BONNe**
Future request #193

### CODE REVIEW

**Comment by Aktanusa** [comment]
I will get to this but it may be a bit as I get my life sorted...

**Comment by Stanzilla** [comment]
@BONNe hey, could you resolve the conflicts, please? I'd love to test it

**Comment by Stanzilla** [comment]
I can't really get the new stuff to show up, loading via `https://cdn.jsdelivr.net/gh/BONNe/CookieMonster@60e7b91c26bc98a740768c116114abef04080345/CookieMonster.js`

**Comment by BONNe** [comment]
Now it should work.

**Comment by Stanzilla** [comment]
Hrm can you post a screenshot how it looks for you?

**Comment by BONNe** [comment]
settings

menu

**Comment by Stanzilla** [comment]
Ohhh, it was off by default! Alright, working fine :)

**Comment by Aktanusa** [comment]
Sorry to be like a broken record, but I will add this sometime.  Sorry for the delay =(.

**Comment by Stanzilla** [comment]
@Aktanusa please merge it, I've been using it for ages without issue

**Comment by Aktanusa** [comment]
Oh yeah, forgot about this.  Thanks.  I'll take a look again.

**Comment by Aktanusa** [comment]
Sorry that I never got around to this.  Thanks for your contribution.  I still think this is helpful.

**Pull request closed without merging**
